/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:35:00 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID DXF_IMPORT_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window DXF_IMPORT_WINDOW ("DXF Import options")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
DXF_IMPORT_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
DXF_IMPORT_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
		      DXFHANDLE dxfData;
		      FILE_SPEC *dxfFile = (FILE_SPEC *) xvt_vobj_get_data(xdWindow);
		      double blockSize;
		      char label[100];
		      ftype matrix[4][4];
		      
		      addWinToStack (xdWindow);
		      
		      xvt_fsys_set_dir(&(dxfFile->dir));
		      DXFread(&dxfData, dxfFile->name);
		      if (dxfData.resultFlags)
		         return (FALSE);  /* Errors have occured */
		      DXFvolOrient(&dxfData);
		      setIdentity(matrix);
		      DXFvolConv(&dxfData, matrix, FALSE);
		      
		      updateFloatTextField (xdWindow, DXF_IMPORT_MIN_X, (double) dxfData.min[0], 1);
		      updateFloatTextField (xdWindow, DXF_IMPORT_MIN_Y, (double) dxfData.min[1], 1);
		      updateFloatTextField (xdWindow, DXF_IMPORT_MIN_Z, (double) dxfData.min[2], 1);
		      updateFloatTextField (xdWindow, DXF_IMPORT_MAX_X, (double) dxfData.max[0], 1);
		      updateFloatTextField (xdWindow, DXF_IMPORT_MAX_Y, (double) dxfData.max[1], 1);
		      updateFloatTextField (xdWindow, DXF_IMPORT_MAX_Z, (double) dxfData.max[2], 1);
		      updateFloatTextField (xdWindow, DXF_IMPORT_MAX_Z, (double) dxfData.max[2], 1);
		      blockSize = (dxfData.max[0] - dxfData.min[0])/10.0;
		      updateFloatTextField (xdWindow, DXF_IMPORT_BLOCK, (double) blockSize, 1);
		      if (blockSize > 1.0)
		      {
		         sprintf(label, "(%dx%dx%d cubes)",
		                  (int) floor((dxfData.max[0] - dxfData.min[0])/blockSize),
		                  (int) floor((dxfData.max[1] - dxfData.min[1])/blockSize),
		                  (int) floor((dxfData.max[2] - dxfData.min[2])/blockSize));
		         xvt_vobj_set_title (xvt_win_get_ctl (xdWindow, DXF_IMPORT_NUM_CUBES), label);
		      }
		      DXFfree(&dxfData);
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
		      takeWinFromStack (xdWindow);
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		      /*
		         Window has lost or gained focus.
		      */
		      if (xdEvent->v.active) {
		         /*
		            Window has gained focus
		         */
		      } else {
		         /*
		            Window has lost focus
		         */
		      }
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		      xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		      xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
		         /* *********************************************** */
		         /* make a RETURN key activate the window OK Button */
		      if (xdEvent->v.chr.ch == '\r')
		      {
		         xdEvent->type = E_CONTROL;
		         xdEvent->v.ctl.id = DXF_IMPORT_WINDOW_PUSHBUTTON_127;
		         xvt_win_dispatch_event (xdWindow, xdEvent);
		      }
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		      /*
		         Horizontal scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		      /*
		         Vertical scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		      /*
		         No menubar was associated with this window
		      */
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case DXF_IMPORT_BLOCK: /* "blockSize" */
			{
			/* TAG BEGIN DXF_IMPORT_BLOCK EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         double minX, minY, minZ;
			         double maxX, maxY, maxZ;
			         double cubeSize;
			         char label[100];
			         minX = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MIN_X);
			         minY = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MIN_Y);
			         minZ = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MIN_Z);
			         maxX = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MAX_X);
			         maxY = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MAX_Y);
			         maxZ = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MAX_Z);
			         cubeSize = getFloatTextFieldValue (xdWindow, DXF_IMPORT_BLOCK);
			         if (cubeSize > 1.000)
			         {
			            sprintf(label, "(%dx%dx%d cubes)",
			                     (int) floor ((maxX-minX)/cubeSize),
			                     (int) floor ((maxY-minY)/cubeSize),
			                     (int) floor ((maxZ-minZ)/cubeSize));
			         }
			         else if (cubeSize > 0.0)
			         {
			            sprintf(label, "(%dx%dx%d cubes)",
			                     (int) floor ((maxX-minX)/cubeSize),
			                     (int) floor ((maxY-minY)/cubeSize),
			                     (int) floor ((maxZ-minZ)/cubeSize));
			         }
			         else
			            strcpy (label, "");
			         xvt_vobj_set_title (xvt_win_get_ctl (xdWindow, DXF_IMPORT_NUM_CUBES), label);
			         }
			/* TAG END DXF_IMPORT_BLOCK EVNT:Control */
			}
			break;
		case DXF_IMPORT_WINDOW_PUSHBUTTON_127: /* "OK" */
			{
			/* TAG BEGIN DXF_IMPORT_WINDOW_PUSHBUTTON_127 EVNT:Control */
			         FILE_SPEC *inFile;
			         FILE_SPEC outFile;
			         int nx, ny, nz;
			         double minX, minY, minZ;
			         double maxX, maxY, maxZ;
			         double cubeSize;
			         inFile = (FILE_SPEC *) xvt_vobj_get_data (xdWindow);
			         strcpy(outFile.name, inFile->name);  /* Use varient of input name as output name */
			         addFileExtention(outFile.name, ".g00");
#if (XVTWS == MACWS)
			         strcpy (outFile.type, "TEXT");
#else
			         strcpy (outFile.type, "g00");
#endif
			         getDefaultDirectory(&(outFile.dir));
			         switch (xvt_dm_post_file_save(&outFile, "Save Block as ...")) {
			         case FL_OK:
			            if (strlen(outFile.name) == 0)
			            {
			               xvt_dm_post_error ("Error, No file Specified");
			               break;
			            }
			            setDefaultDirectory(&(outFile.dir));
			            xvt_fsys_set_dir(&outFile.dir);
			            break;
			         case FL_BAD:
			            return (0L);
			            break;
			         case FL_CANCEL:
			            return (0L);
			            break;
			         }
			         
			                  /* ********************************** */
			                  /* save all the options in the window */
			         minX = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MIN_X);
			         minY = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MIN_Y);
			         minZ = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MIN_Z);
			         maxX = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MAX_X);
			         maxY = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MAX_Y);
			         maxZ = getFloatTextFieldValue (xdWindow, DXF_IMPORT_MAX_Z);
			         cubeSize = getFloatTextFieldValue (xdWindow, DXF_IMPORT_BLOCK);
			         nx = (int) floor ((maxX - minX)/cubeSize);
			         ny = (int) floor ((maxY - minY)/cubeSize);
			         nz = (int) floor ((maxZ - minZ)/cubeSize);
			         xvt_vobj_destroy(xdWindow);
			         convertDXFBlock(inFile, &outFile, nx, ny, nz, minX, minY, maxZ, cubeSize);
			         xvt_mem_free ((char *) inFile);
			/* TAG END DXF_IMPORT_WINDOW_PUSHBUTTON_127 EVNT:Control */
			}
			break;
		case DXF_IMPORT_WINDOW_PUSHBUTTON_129: /* "Help..." */
			{
			/* TAG BEGIN DXF_IMPORT_WINDOW_PUSHBUTTON_129 EVNT:Control */
			displayHelp("dxfimp.htm");
			/* TAG END DXF_IMPORT_WINDOW_PUSHBUTTON_129 EVNT:Control */
			}
			break;
		case DXF_IMPORT_WINDOW_PUSHBUTTON_130: /* "Cancel" */
			{
			/* TAG BEGIN DXF_IMPORT_WINDOW_PUSHBUTTON_130 EVNT:Control */
			            /* ******************************************************* */
			            /* restore the options that were saved when first poped up */
			         xvt_mem_free ((char *) xvt_vobj_get_data(xdWindow));
			         xvt_vobj_destroy(xdWindow);
			/* TAG END DXF_IMPORT_WINDOW_PUSHBUTTON_130 EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		      switch (xdEvent->v.user.id) {
		      case -1:
		      default:
		         break;
		      }
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	   xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
