/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:34:59 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID EVENT_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window EVENT_WINDOW ("Event Options")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
EVENT_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
EVENT_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
			/* put this window in the created heirachy */
		addWinToStack (xdWindow);
		createEventOptions (xdWindow, (OBJECT *) xvt_vobj_get_data (xdWindow));
		makeEditOptionsHistory ((OBJECT *) xvt_vobj_get_data (xdWindow));
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
			/* take this window out of the created heirachy */
		takeWinFromStack (xdWindow);
		removeEditOptionsHistory ((OBJECT *) xvt_vobj_get_data (xdWindow));
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		/*
			Window has lost or gained focus.
		*/
		if (xdEvent->v.active) {
			/*
				Window has gained focus
			*/
		} else {
			/*
				Window has lost focus
			*/
		}
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		WINDOW previewWin;
		xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		updateEventOptions (xdWindow, (OBJECT *) xvt_vobj_get_data (xdWindow));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
			/* *********************************************** */
			/* make a RETURN key activate the window OK Button */
		if (xdEvent->v.chr.ch == '\r')
		{
		   xdEvent->type = E_CONTROL;
		   xdEvent->v.ctl.id = EVENT_OK;
		   xvt_win_dispatch_event (xdWindow, xdEvent);
		}
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		eventOptionsMouseUp (xdWindow, &(xdEvent->v.mouse));
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		/*
			Horizontal scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		/*
			Vertical scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		/*
			No menubar was associated with this window
		*/
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case EVENT_OK: /* "OK" */
			{
			/* TAG BEGIN EVENT_OK EVNT:Control */
						/* ********************************** */
						/* save all the options in the window */
			saveEventOptions (xdWindow, (OBJECT *) xvt_vobj_get_data (xdWindow), FALSE);
			xvt_vobj_destroy(xdWindow);
			/* TAG END EVENT_OK EVNT:Control */
			}
			break;
		case EVENT_NAME: /* "Lineation" */
			{
			/* TAG BEGIN EVENT_NAME EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			}
			/* TAG END EVENT_NAME EVNT:Control */
			}
			break;
		case EVENT_CANCEL: /* "Cancel" */
			{
			/* TAG BEGIN EVENT_CANCEL EVNT:Control */
			OBJECT *data = (OBJECT *) xvt_vobj_get_data (xdWindow);
			             /* destroy window before deleteing object as it is needed to get
			            ** rid of the fake stop inserted in the history */
			xvt_vobj_destroy(xdWindow);
			if (data->newObject)
			   deleteObject (NULL_WIN, data);
			else	/* restore the options that were saved when first poped up */
			   copyOptions (EVENT_WINDOW, data, OPTIONS_RESTORE);
			/* TAG END EVENT_CANCEL EVNT:Control */
			}
			break;
		case EVENT_HELP: /* "Help..." */
			{
			/* TAG BEGIN EVENT_HELP EVNT:Control */
			displayEventHelp ((OBJECT *) xvt_vobj_get_data (xdWindow));
			/* TAG END EVENT_HELP EVNT:Control */
			}
			break;
		case EVENT_OPTION_SELECTION: /* "Option Selection" */
			{
			/* TAG BEGIN EVENT_OPTION_SELECTION EVNT:Control */
			selectEventGroup (xdWindow, (OBJECT *) xvt_vobj_get_data (xdWindow),
			                              xvt_list_get_sel_index(xvt_win_get_ctl(xdWindow, xdControlId)));
			/* TAG END EVENT_OPTION_SELECTION EVNT:Control */
			}
			break;
		case EVENT_PREVIOUS: /* "Previous Event" */
			{
			/* TAG BEGIN EVENT_PREVIOUS EVNT:Control */
			OBJECT *object = (OBJECT *) xvt_vobj_get_data (xdWindow);
			OBJECT *prevObject, *nextObject = NULL;
			
						/* save all the options in the window */
			saveEventOptions (xdWindow, object, FALSE);
			xvt_vobj_destroy(xdWindow);
						/* Open previous event */
			for (prevObject = nthObject (NULL_WIN, 0); prevObject && (nextObject != object); prevObject = nextObject)
			{
			   for (nextObject = prevObject->next; nextObject && (nextObject->shape == STOP); nextObject = nextObject->next)
			      ;  /* Move to next Editable event */
			   if (nextObject == object)  /* Get out if we have found the current object as prevObject is the one before */
			      break;
			}
			
			if (prevObject) /* we have a previous object that is editable */
			   editObjectParams (prevObject);
			/* TAG END EVENT_PREVIOUS EVNT:Control */
			}
			break;
		case EVENT_NEXT: /* "Next Event" */
			{
			/* TAG BEGIN EVENT_NEXT EVNT:Control */
			OBJECT *object = (OBJECT *) xvt_vobj_get_data (xdWindow);
			
						/* save all the options in the window */
			saveEventOptions (xdWindow, object, FALSE);
			xvt_vobj_destroy(xdWindow);
						/* Open next event */
			do {
				object = object->next;
			} while (object && (object->shape == STOP));
			
			if (object) /* we have a next object that is editable */
			   editObjectParams (object);
			/* TAG END EVENT_NEXT EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		switch (xdEvent->v.user.id) {
		case -1:
		default:
			break;
		}
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
