/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:34:59 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	This function is the menu event handler for menu MENU_BAR_2
*/

void
#if XVT_CC_PROTO
do_MENU_BAR_2 (WINDOW xdWindow, EVENT *xdEvent)
#else
do_MENU_BAR_2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	MENU_TAG tag = xdEvent->v.cmd.tag;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (tag) {
	case -1:
	default:
		{
		/* TAG BEGIN SPCL:Default */
		xvt_win_dispatch_event(TASK_WIN, xdEvent);
		/* TAG END SPCL:Default */
		}
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
	/* TAG END SPCL:Bottom */
}
