/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:34:59 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID PROJECT_OPTIONS_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window PROJECT_OPTIONS_WINDOW ("Project Options")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
PROJECT_OPTIONS_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
PROJECT_OPTIONS_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	extern PROJECT_OPTIONS projectOptions;
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
			/* put this window in the created heirachy */
		addWinToStack (xdWindow);
		loadProjectOptions (xdWindow);
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
			/* take this window out of the created heirachy */
		takeWinFromStack (xdWindow);
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		/*
			Window has lost or gained focus.
		*/
		if (xdEvent->v.active) {
			/*
				Window has gained focus
			*/
		} else {
			/*
				Window has lost focus
			*/
		}
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
			/* *********************************************** */
			/* make a RETURN key activate the window OK Button */
		if (xdEvent->v.chr.ch == '\r')
		{
		   xdEvent->type = E_CONTROL;
		   xdEvent->v.ctl.id = PROJECT_OPTIONS_OK;
		   xvt_win_dispatch_event (xdWindow, xdEvent);
		}
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		/*
			Horizontal scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		/*
			Vertical scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		/*
			No menubar was associated with this window
		*/
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case PROJECT_OPTIONS_OK: /* "OK" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_OK EVNT:Control */
			saveProjectOptions (xdWindow);
			xvt_vobj_destroy(xdWindow);
			/* TAG END PROJECT_OPTIONS_OK EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_CANCEL: /* "Cancel" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_CANCEL EVNT:Control */
			OBJECT *data = (OBJECT *) xvt_vobj_get_data (xdWindow);
				/* ******************************************************* */
				/* restore the options that were saved when first poped up */
			copyOptions (PROJECT_OPTIONS_WINDOW, (OBJECT *) &projectOptions, OPTIONS_RESTORE);
			xvt_vobj_destroy(xdWindow);
			/* TAG END PROJECT_OPTIONS_CANCEL EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_HELP: /* "Help..." */
			{
			/* TAG BEGIN PROJECT_OPTIONS_HELP EVNT:Control */
			displayHelp("projop.htm");
			/* TAG END PROJECT_OPTIONS_HELP EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_WINDOW_C10: /* "Metres" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_WINDOW_C10 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				PROJECT_OPTIONS_WINDOW_C10,
				PROJECT_OPTIONS_WINDOW_C10,
				PROJECT_OPTIONS_WINDOW_C11);
			/* TAG END PROJECT_OPTIONS_WINDOW_C10 EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_WINDOW_C11: /* "Feet" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_WINDOW_C11 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				PROJECT_OPTIONS_WINDOW_C11,
				PROJECT_OPTIONS_WINDOW_C10,
				PROJECT_OPTIONS_WINDOW_C11);
			/* TAG END PROJECT_OPTIONS_WINDOW_C11 EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_WINDOW_C13: /* "s.i." */
			{
			/* TAG BEGIN PROJECT_OPTIONS_WINDOW_C13 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				PROJECT_OPTIONS_WINDOW_C13,
				PROJECT_OPTIONS_WINDOW_C13,
				PROJECT_OPTIONS_WINDOW_C14);
			/* TAG END PROJECT_OPTIONS_WINDOW_C13 EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_WINDOW_C14: /* "c.g.s." */
			{
			/* TAG BEGIN PROJECT_OPTIONS_WINDOW_C14 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				PROJECT_OPTIONS_WINDOW_C14,
				PROJECT_OPTIONS_WINDOW_C13,
				PROJECT_OPTIONS_WINDOW_C14);
			/* TAG END PROJECT_OPTIONS_WINDOW_C14 EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_REMOTE: /* "Remote" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_REMOTE EVNT:Control */
			WINDOW win;
			OBJECT *data = (OBJECT *) xvt_vobj_get_data (xdWindow);
			xdCheckRadioButton(xdWindow, PROJECT_OPTIONS_REMOTE,
				PROJECT_OPTIONS_REMOTE, PROJECT_OPTIONS_LOCAL);
			if (!(win = createCenteredWindow(PARALLEL_OPTIONS_WINDOW, TASK_WIN, EM_ALL, PARALLEL_OPTIONS_WINDOW_eh, (long) data)))
			   xvt_dm_post_error("Can't open window");
			/* TAG END PROJECT_OPTIONS_REMOTE EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_LOCAL: /* "Local" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_LOCAL EVNT:Control */
			xdCheckRadioButton(xdWindow, PROJECT_OPTIONS_LOCAL,
				PROJECT_OPTIONS_REMOTE, PROJECT_OPTIONS_LOCAL);
			/* TAG END PROJECT_OPTIONS_LOCAL EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_PRINT_SCALE: /* "print scale" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_PRINT_SCALE EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/* 
					Contents of control were changed
				*/
			}
			/* TAG END PROJECT_OPTIONS_PRINT_SCALE EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_NEW_WINDOWS: /* "New window each time" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_NEW_WINDOWS EVNT:Control */
			WINDOW ctl_win = xvt_win_get_ctl(xdWindow, PROJECT_OPTIONS_NEW_WINDOWS);
			xvt_ctl_set_checked(ctl_win, (BOOLEAN) (!xvt_ctl_is_checked(ctl_win)));
			/* TAG END PROJECT_OPTIONS_NEW_WINDOWS EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_GRAVITY: /* "Gravity" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_GRAVITY EVNT:Control */
			WINDOW ctl_win = xvt_win_get_ctl(xdWindow, PROJECT_OPTIONS_GRAVITY);
			xvt_ctl_set_checked(ctl_win, (BOOLEAN) (!xvt_ctl_is_checked(ctl_win)));
			/* TAG END PROJECT_OPTIONS_GRAVITY EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_MAGNETICS: /* "Magnetics" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_MAGNETICS EVNT:Control */
			WINDOW ctl_win = xvt_win_get_ctl(xdWindow, PROJECT_OPTIONS_MAGNETICS);
			xvt_ctl_set_checked(ctl_win, (BOOLEAN) (xvt_ctl_is_checked(ctl_win)));
			/* TAG END PROJECT_OPTIONS_MAGNETICS EVNT:Control */
			}
			break;
		case PROJECT_OPTIONS_IMAGE_SCALE: /* "imagescale" */
			{
			/* TAG BEGIN PROJECT_OPTIONS_IMAGE_SCALE EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/* 
					Contents of control were changed
				*/
			}
			/* TAG END PROJECT_OPTIONS_IMAGE_SCALE EVNT:Control */
			}
			break;
		case PROJECT_MOVIE_OPTIONS_BUT: /* "Movie Options..." */
			{
			/* TAG BEGIN PROJECT_MOVIE_OPTIONS_BUT EVNT:Control */
			OBJECT *data = (OBJECT *) xvt_vobj_get_data (xdWindow);
			WINDOW win;
			if (!(win = createCenteredWindow(MOVIE_OPTIONS, TASK_WIN, EM_ALL, MOVIE_OPTIONS_eh, (long) data)))
				 xvt_dm_post_error("Can't open window");
			 
			/* TAG END PROJECT_MOVIE_OPTIONS_BUT EVNT:Control */
			}
			break;
		case PROJECT_GRV_DISP_OPTIONS: /* "Gravity Display..." */
			{
			/* TAG BEGIN PROJECT_GRV_DISP_OPTIONS EVNT:Control */
			OBJECT *data = (OBJECT *) xvt_vobj_get_data (xdWindow);
			WINDOW win;
			if (!(win = createCenteredWindow(IMAGE_OPTION_WINDOW,
			                            TASK_WIN, EM_ALL, IMAGE_OPTION_WINDOW_eh,
			                           (long) &(projectOptions.gravityDisplay))))
				 xvt_dm_post_error("Can't open window");
			/* TAG END PROJECT_GRV_DISP_OPTIONS EVNT:Control */
			}
			break;
		case PROJECT_WINDOW_BACKGROUND: /* "Set Window Background..." */
			{
			/* TAG BEGIN PROJECT_WINDOW_BACKGROUND EVNT:Control */
			WINDOW win;
			if (!(win = createCenteredWindow(DEFINE_COLOUR_WINDOW, TASK_WIN, EM_ALL,
			                                                      DEFINE_COLOUR_WINDOW_eh, xvt_vobj_get_data (xdWindow))))
				xvt_dm_post_error("Can't open window");
			/* TAG END PROJECT_WINDOW_BACKGROUND EVNT:Control */
			}
			break;
		case PROJECT_MAG_DISP_OPTIONS: /* "Magnetic Display..." */
			{
			/* TAG BEGIN PROJECT_MAG_DISP_OPTIONS EVNT:Control */
			OBJECT *data = (OBJECT *) xvt_vobj_get_data (xdWindow);
			WINDOW win;
			if (!(win = createCenteredWindow(IMAGE_OPTION_WINDOW,
			                            TASK_WIN, EM_ALL, IMAGE_OPTION_WINDOW_eh,
			                           (long) &(projectOptions.magneticsDisplay))))
				 xvt_dm_post_error("Can't open window");
			/* TAG END PROJECT_MAG_DISP_OPTIONS EVNT:Control */
			}
			break;
		case PROJECT_EASTING: /* "east" */
			{
			/* TAG BEGIN PROJECT_EASTING EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/* 
					Contents of control were changed
				*/
			}
			/* TAG END PROJECT_EASTING EVNT:Control */
			}
			break;
		case PROJECT_NORTHING: /* "north" */
			{
			/* TAG BEGIN PROJECT_NORTHING EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/* 
					Contents of control were changed
				*/
			}
			/* TAG END PROJECT_NORTHING EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		switch (xdEvent->v.user.id) {
		case -1:
		default:
			break;
		}
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
