/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:35:00 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID ASCII_IMAGE_OPTIONS
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window ASCII_IMAGE_OPTIONS ("Reference Image")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
ASCII_IMAGE_OPTIONS_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
ASCII_IMAGE_OPTIONS_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		      /*
		         Window has lost or gained focus.
		      */
		      if (xdEvent->v.active) {
		         /*
		            Window has gained focus
		         */
		      } else {
		         /*
		            Window has lost focus
		         */
		      }
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		      xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		      xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
		         /* *********************************************** */
		         /* make a RETURN key activate the window OK Button */
		      if (xdEvent->v.chr.ch == '\r')
		      {
		         xdEvent->type = E_CONTROL;
		         xdEvent->v.ctl.id = ASCII_IMAGE_OPTION_OK;
		         xvt_win_dispatch_event (xdWindow, xdEvent);
		      }
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		      /*
		         Horizontal scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		      /*
		         Vertical scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		      /*
		         No menubar was associated with this window
		      */
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case ASCII_ROWS: /* "48" */
			{
			/* TAG BEGIN ASCII_ROWS EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_ROWS EVNT:Control */
			}
			break;
		case ASCII_COLS: /* "63" */
			{
			/* TAG BEGIN ASCII_COLS EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_COLS EVNT:Control */
			}
			break;
		case ASCII_CELL_SIZE: /* "200" */
			{
			/* TAG BEGIN ASCII_CELL_SIZE EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_CELL_SIZE EVNT:Control */
			}
			break;
		case ASCII_IMAGE_OPTION_CANCEL: /* "Cancel" */
			{
			/* TAG BEGIN ASCII_IMAGE_OPTION_CANCEL EVNT:Control */
			         xvt_vobj_destroy (xdWindow);
			/* TAG END ASCII_IMAGE_OPTION_CANCEL EVNT:Control */
			}
			break;
		case ASCII_IMAGE_OPTION_OK: /* "OK" */
			{
			/* TAG BEGIN ASCII_IMAGE_OPTION_OK EVNT:Control */
			         int nx, ny, type, flipXY;
			         double cellSize, northing, easting, inclination, declination, intensity, altitude;
			         FILE_SPEC inFile, outFile;
			         
			         nx = getIntegerTextFieldValue(xdWindow, ASCII_COLS);
			         ny = getIntegerTextFieldValue(xdWindow, ASCII_ROWS);
			         cellSize = getFloatTextFieldValue(xdWindow, ASCII_CELL_SIZE);
			         easting = getFloatTextFieldValue(xdWindow, ASCII_IMAGE_EASTING);
			         northing = getFloatTextFieldValue(xdWindow, ASCII_IMAGE_NORTHING);
			         inclination = getFloatTextFieldValue(xdWindow, ASCII_IMAGE_INCLINATION);
			         declination = getFloatTextFieldValue(xdWindow, ASCII_IMAGE_DECLINATION);
			         intensity = getFloatTextFieldValue(xdWindow, ASCII_IMAGE_INTENSITY);
			         altitude = getFloatTextFieldValue(xdWindow, ASCII_IMAGE_ALTITUDE);
			         type = xvt_ctl_is_checked(xvt_win_get_ctl(xdWindow, ASCII_IMAGE_MAGNETICS));
			         flipXY = xvt_ctl_is_checked(xvt_win_get_ctl(xdWindow, ASCII_IMAGE_FLIP_XY));
			         {
#if (XVTWS == MACWS)
			            strcpy (inFile.type, "TEXT");
#else
			            strcpy (inFile.type, "asc");
#endif
			            getDefaultDirectory(&(inFile.dir));
			            switch (xvt_dm_post_file_open(&inFile, "Read Ascii Image from ...")) {
			            case FL_OK:
			               if (strlen(inFile.name) == 0)
			               {
			                  xvt_dm_post_error ("Error, No file Specified");
			                  break;
			               }
			               setDefaultDirectory(&(inFile.dir));
			               break;
			            case FL_BAD:
			               xvt_dm_post_error("Error getting file name.");
			               return 0L;
			               break;
			            case FL_CANCEL:
			               return 0L;
			               break;
			            }
			         }
			         
			         {
			            strcpy (outFile.name, inFile.name);
			            if (type == 0) /* Gravity */
			               addFileExtention (outFile.name, "grv");
			            else
			               addFileExtention (outFile.name, "mag");
#if (XVTWS == MACWS)
			            strcpy (outFile.type, "TEXT");
#else
			            if (type == 0) /* Gravity */
			               strcpy (outFile.type, "grv");
			            else
			               strcpy (outFile.type, "mag");
#endif
			            getDefaultDirectory(&(outFile.dir));
			            switch (xvt_dm_post_file_save(&outFile, "Write Image as ...")) {
			            case FL_OK:
			               if (strlen(outFile.name) == 0)
			               {
			                  xvt_dm_post_error ("Error, No file Specified");
			                  break;
			               }
			               setDefaultDirectory(&(outFile.dir));
			               break;
			            case FL_BAD:
			               xvt_dm_post_error("Error getting file name.");
			               return 0L;
			               break;
			            case FL_CANCEL:
			               return 0L;
			               break;
			            }
			         }
			                  /* ********************************** */
			                  /* save all the options in the window */
			         if (convertAsciiImage (&inFile, &outFile, type, nx, ny, flipXY, cellSize, easting, northing,
			                                        inclination, declination, intensity, altitude))
			         {
			            displayAnomaliesImage (outFile.name, NULL);
			         }
			         
			         xvt_vobj_destroy (xdWindow);
			/* TAG END ASCII_IMAGE_OPTION_OK EVNT:Control */
			}
			break;
		case ASCII_IMAGE_OPTION_HELP: /* "Help..." */
			{
			/* TAG BEGIN ASCII_IMAGE_OPTION_HELP EVNT:Control */
			displayHelp("refdat.htm");
			/* TAG END ASCII_IMAGE_OPTION_HELP EVNT:Control */
			}
			break;
		case ASCII_IMAGE_EASTING: /* "0" */
			{
			/* TAG BEGIN ASCII_IMAGE_EASTING EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_IMAGE_EASTING EVNT:Control */
			}
			break;
		case ASCII_IMAGE_NORTHING: /* "0" */
			{
			/* TAG BEGIN ASCII_IMAGE_NORTHING EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_IMAGE_NORTHING EVNT:Control */
			}
			break;
		case ASCII_IMAGE_INCLINATION: /* "-67.0" */
			{
			/* TAG BEGIN ASCII_IMAGE_INCLINATION EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_IMAGE_INCLINATION EVNT:Control */
			}
			break;
		case ASCII_IMAGE_DECLINATION: /* "0.0" */
			{
			/* TAG BEGIN ASCII_IMAGE_DECLINATION EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_IMAGE_DECLINATION EVNT:Control */
			}
			break;
		case ASCII_IMAGE_INTENSITY: /* "63000.0" */
			{
			/* TAG BEGIN ASCII_IMAGE_INTENSITY EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_IMAGE_INTENSITY EVNT:Control */
			}
			break;
		case ASCII_IMAGE_ALTITUDE: /* "80" */
			{
			/* TAG BEGIN ASCII_IMAGE_ALTITUDE EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /* 
			               Contents of control were changed
			            */
			         }
			/* TAG END ASCII_IMAGE_ALTITUDE EVNT:Control */
			}
			break;
		case ASCII_IMAGE_GRAVITY: /* "Gravity Data" */
			{
			/* TAG BEGIN ASCII_IMAGE_GRAVITY EVNT:Control */
			         xdCheckRadioButton(xdWindow,
			            ASCII_IMAGE_GRAVITY,
			            ASCII_IMAGE_GRAVITY,
			            ASCII_IMAGE_MAGNETICS);
			/* TAG END ASCII_IMAGE_GRAVITY EVNT:Control */
			}
			break;
		case ASCII_IMAGE_MAGNETICS: /* "Magnetics Data" */
			{
			/* TAG BEGIN ASCII_IMAGE_MAGNETICS EVNT:Control */
			         xdCheckRadioButton(xdWindow,
			            ASCII_IMAGE_MAGNETICS,
			            ASCII_IMAGE_GRAVITY,
			            ASCII_IMAGE_MAGNETICS);
			/* TAG END ASCII_IMAGE_MAGNETICS EVNT:Control */
			}
			break;
		case ASCII_IMAGE_FLIP_XY: /* "Flip X-Y Axis" */
			{
			/* TAG BEGIN ASCII_IMAGE_FLIP_XY EVNT:Control */
			WINDOW ctl_win = xvt_win_get_ctl(xdWindow, ASCII_IMAGE_FLIP_XY);
			xvt_ctl_set_checked(ctl_win, !xvt_ctl_is_checked(ctl_win));
			/* TAG END ASCII_IMAGE_FLIP_XY EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		      switch (xdEvent->v.user.id) {
		      case -1:
		      default:
		         break;
		      }
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	   xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
