/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:35:00 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID SURFACE_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window SURFACE_WINDOW ("Surface Import")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
SURFACE_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
SURFACE_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
		      setScrollRange (xdWindow, SURFACE_XDIM_BAR, 0, 20000);
		      setScrollRange (xdWindow, SURFACE_YDIM_BAR, 0, 20000);
		      setScrollRange (xdWindow, SURFACE_ZDIM_BAR, 0, 20000);
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		      /*
		         Window has lost or gained focus.
		      */
		      if (xdEvent->v.active) {
		         /*
		            Window has gained focus
		         */
		      } else {
		         /*
		            Window has lost focus
		         */
		      }
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		      xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		      xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
		         /* *********************************************** */
		         /* make a RETURN key activate the window OK Button */
		      if (xdEvent->v.chr.ch == '\r')
		      {                              /* Pass the event down the window heirachy */
		         xvt_win_dispatch_event (xvt_vobj_get_parent(xdWindow), xdEvent);
		      }
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		      /*
		         Horizontal scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		      /*
		         Vertical scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		      /*
		         No menubar was associated with this window
		      */
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case SURFACE_VIEW: /* "View..." */
			{
			/* TAG BEGIN SURFACE_VIEW EVNT:Control */
			         WINDOW win;
			         RCT rect;
			         xvt_rect_set (&rect, 20, 20, 250, 250);
			         if (win = xvt_win_create (W_DOC, &rect, "Surface Plane", 0, TASK_WIN,
			                                                 WSF_NO_MENUBAR | WSF_CLOSE | WSF_SIZE,
			                                                 EM_ALL, pictureEventHandler, 0L))
			             view3dSurface (win, (OBJECT *) xvt_vobj_get_data (xdWindow));
			/* TAG END SURFACE_VIEW EVNT:Control */
			}
			break;
		case SURFACE_TYPE_LIST: /* "surface type" */
			{
			/* TAG BEGIN SURFACE_TYPE_LIST EVNT:Control */
			         char label[100];
			         WINDOW surfTypeWin;
			         OBJECT *object = (OBJECT *) xvt_vobj_get_data (xdWindow);
			         surfTypeWin = xvt_win_get_ctl(xdWindow, SURFACE_TYPE_LIST);
			         xvt_list_get_first_sel (surfTypeWin, label, 100);
			         if (strstr (label, "DXF"))
			         {
			            static FILE_SPEC fs;
#if (XVTWS == MACWS)
			            strcpy (fs.type, "TEXT");
#else
			            strcpy (fs.type, "dxf");
#endif
			            getDefaultDirectory(&(fs.dir));
			            switch (xvt_dm_post_file_open(&fs, "Read Surface from ...")) {
			            case FL_OK:
			               if (strlen(fs.name) == 0)
			               {
			                  xvt_dm_post_error ("Error, No file Specified");
			                  break;
			               }
			               setDefaultDirectory(&(fs.dir));
			               if (!load3dSurface (&fs, object, NULL))
			                  xvt_list_set_sel (surfTypeWin, 0, TRUE);
			               else
			               {
			                  DXFHANDLE *dxfData;
			                  if (dxfData = getDxfSurfaceStructure (object))
			                  {
			                     updateFloatTextField (xdWindow, SURFACE_XDIM, (double) dxfData->aspect[0], 1);
			                     updateFloatTextField (xdWindow, SURFACE_YDIM, (double) dxfData->aspect[1], 1);
			                     updateFloatTextField (xdWindow, SURFACE_ZDIM, (double) dxfData->aspect[2], 1);
			                  }
			               }
			               break;
			            case FL_BAD:
			               xvt_dm_post_error("Error getting file name.");
			               xvt_list_set_sel (surfTypeWin, 0, TRUE);
			               break;
			            case FL_CANCEL:
			               xvt_list_set_sel (surfTypeWin, 0, TRUE);
			               break;
			            }
			         }
			         if (object->shape == FAULT)
			            updateFaultOptions ((OBJECT *) xvt_vobj_get_data (xdWindow));
			         if (object->shape == SHEAR_ZONE)
			            updateShearOptions ((OBJECT *) xvt_vobj_get_data (xdWindow));
			         if (object->shape == UNCONFORMITY)
			            updateUnconformityOptions ((OBJECT *) xvt_vobj_get_data (xdWindow));
			/* TAG END SURFACE_TYPE_LIST EVNT:Control */
			}
			break;
		case SURFACE_XDIM_BAR: /* "x bar" */
			{
			/* TAG BEGIN SURFACE_XDIM_BAR EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos,1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos,1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, SURFACE_XDIM, pos);
			/* TAG END SURFACE_XDIM_BAR EVNT:Control */
			}
			break;
		case SURFACE_XDIM: /* "x" */
			{
			/* TAG BEGIN SURFACE_XDIM EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, SURFACE_XDIM_BAR, SURFACE_XDIM, FALSE);
			         }
			/* TAG END SURFACE_XDIM EVNT:Control */
			}
			break;
		case SURFACE_YDIM_BAR: /* "y bar" */
			{
			/* TAG BEGIN SURFACE_YDIM_BAR EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos,1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos,1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, SURFACE_YDIM, pos);
			/* TAG END SURFACE_YDIM_BAR EVNT:Control */
			}
			break;
		case SURFACE_YDIM: /* "y" */
			{
			/* TAG BEGIN SURFACE_YDIM EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, SURFACE_YDIM_BAR, SURFACE_YDIM, FALSE);
			         }
			/* TAG END SURFACE_YDIM EVNT:Control */
			}
			break;
		case SURFACE_ZDIM_BAR: /* "z bar" */
			{
			/* TAG BEGIN SURFACE_ZDIM_BAR EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos,1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos,1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, SURFACE_ZDIM, pos);
			/* TAG END SURFACE_ZDIM_BAR EVNT:Control */
			}
			break;
		case SURFACE_ZDIM: /* "z" */
			{
			/* TAG BEGIN SURFACE_ZDIM EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, SURFACE_ZDIM_BAR, SURFACE_ZDIM, FALSE);
			         }
			/* TAG END SURFACE_ZDIM EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		      switch (xdEvent->v.user.id) {
		      case -1:
		      default:
		         break;
		      }
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	   xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
