/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:35:00 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID VIEW_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window VIEW_WINDOW ("Block View Options")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
VIEW_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
VIEW_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
		WINDOW previewWindow;
		int mmin, mmax;
		WINDOW cubeSizes;
			/* put this window in the created heirachy */
		addWinToStack (xdWindow);
		cubeSizes = xvt_win_get_ctl (xdWindow, VIEW_GEOLOGY_CUBE);
		xvt_list_suspend (cubeSizes);
		xvt_list_add (cubeSizes, 0, "50");
		xvt_list_add (cubeSizes, 1, "75");
		xvt_list_add (cubeSizes, 2, "100");
		xvt_list_add (cubeSizes, 3, "150");
		xvt_list_add (cubeSizes, 4, "200");
		xvt_list_add (cubeSizes, 5, "300");
		xvt_list_add (cubeSizes, 6, "400");
		xvt_list_add (cubeSizes, 7, "500");
		xvt_list_add (cubeSizes, 8, "600");
		xvt_list_add (cubeSizes, 9, "700");
		xvt_list_add (cubeSizes, 10, "800");
		xvt_list_add (cubeSizes, 11, "900");
		xvt_list_add (cubeSizes, 12, "1000");
		xvt_list_resume (cubeSizes);
		cubeSizes = xvt_win_get_ctl (xdWindow, VIEW_GEOPHYSICS_CUBE);
		xvt_list_suspend (cubeSizes);
		xvt_list_add (cubeSizes, 0, "50");
		xvt_list_add (cubeSizes, 1, "75");
		xvt_list_add (cubeSizes, 2, "100");
		xvt_list_add (cubeSizes, 3, "150");
		xvt_list_add (cubeSizes, 4, "200");
		xvt_list_add (cubeSizes, 5, "300");
		xvt_list_add (cubeSizes, 6, "400");
		xvt_list_add (cubeSizes, 7, "500");
		xvt_list_add (cubeSizes, 8, "600");
		xvt_list_add (cubeSizes, 9, "700");
		xvt_list_add (cubeSizes, 10, "800");
		xvt_list_add (cubeSizes, 11, "900");
		xvt_list_add (cubeSizes, 12, "1000");
		xvt_list_resume (cubeSizes);
		
			/* ******************************** */
			/* set the ranges of the scrollbars */
							/* **************** */
		mmin = -10000; mmax = 10000;		/* range for Origin */
		setScrollRange (xdWindow, VIEW_ORIGIN_X_BAR, mmin, mmax);
		setScrollRange (xdWindow, VIEW_ORIGIN_Y_BAR, mmin, mmax);
		setScrollRange (xdWindow, VIEW_ORIGIN_Z_BAR, mmin, mmax);
							/* **************** */
		mmin = 1; mmax = 20000;		/* range for Dimensions  */
		setScrollRange (xdWindow, DIM_X_BAR, mmin, mmax);
		setScrollRange (xdWindow, DIM_Y_BAR, mmin, mmax);
		setScrollRange (xdWindow, DIM_Z_BAR, mmin, mmax);
					/* *********************************** */
					/* setup all the options in the window */
		loadViewOptions (xdWindow);
		previewWindow = createPreviewWindow (xdWindow, xvt_win_get_ctl (xdWindow, VIEW_PREVIEW));
		xvt_vobj_set_data (xdWindow, previewWindow);
				/* *************************************************** */
				/* Check the consistency of scrollbars and text fields */
		updateScrollAndText (xdWindow, VIEW_ORIGIN_X_BAR, VIEW_ORIGIN_X, FALSE);
		updateScrollAndText (xdWindow, VIEW_ORIGIN_Y_BAR, VIEW_ORIGIN_Y, FALSE);
		updateScrollAndText (xdWindow, VIEW_ORIGIN_Z_BAR, VIEW_ORIGIN_Z, FALSE);
		updateScrollAndText (xdWindow, DIM_X_BAR, DIM_X, FALSE);
		updateScrollAndText (xdWindow, DIM_Y_BAR, DIM_Y, FALSE);
		updateScrollAndText (xdWindow, DIM_Z_BAR, DIM_Z, FALSE);
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
			/* take this window out of the created heirachy */
		takeWinFromStack (xdWindow);
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		/*
			Window has lost or gained focus.
		*/
		if (xdEvent->v.active) {
			/*
				Window has gained focus
			*/
		} else {
			/*
				Window has lost focus
			*/
		}
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
			/* *********************************************** */
			/* make a RETURN key activate the window OK Button */
		if (xdEvent->v.chr.ch == '\r')
		{
		   xdEvent->type = E_CONTROL;
		   xdEvent->v.ctl.id = VIEW_OK;
		   xvt_win_dispatch_event (xdWindow, xdEvent);
		}
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		/*
			Horizontal scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		/*
			Vertical scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		/*
			No menubar was associated with this window
		*/
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case DIM_X_BAR: /* "Horizontal Scrollbar dX" */
			{
			/* TAG BEGIN DIM_X_BAR EVNT:Control */
			int pos = 0;
			/*
				Horizontal scrollbar control was operated
			*/
			switch (xdEvent->v.ctl.ci.v.scroll.what) {
			case SC_LINE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
				break;
			case SC_LINE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
				break;
			case SC_PAGE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
				SNAP_DOWN_BY(pos, 1000)
				break;
			case SC_PAGE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
				SNAP_UP_BY(pos, 1000)
				break;
			case SC_THUMB:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			case SC_THUMBTRACK:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			}
			updateScrollField (xdWindow, xdControlId, pos);
			updateNumericTextField (xdWindow, DIM_X, pos);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END DIM_X_BAR EVNT:Control */
			}
			break;
		case DIM_Y_BAR: /* "Horizontal Scrollbar dY" */
			{
			/* TAG BEGIN DIM_Y_BAR EVNT:Control */
			int pos = 0;
			/*
				Horizontal scrollbar control was operated
			*/
			switch (xdEvent->v.ctl.ci.v.scroll.what) {
			case SC_LINE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
				break;
			case SC_LINE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
				break;
			case SC_PAGE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
				SNAP_DOWN_BY(pos, 1000)
				break;
			case SC_PAGE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
				SNAP_UP_BY(pos, 1000)
				break;
			case SC_THUMB:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			case SC_THUMBTRACK:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			}
			updateScrollField (xdWindow, xdControlId, pos);
			updateNumericTextField (xdWindow, DIM_Y, pos);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END DIM_Y_BAR EVNT:Control */
			}
			break;
		case DIM_Z_BAR: /* "Horizontal Scrollbar dZ" */
			{
			/* TAG BEGIN DIM_Z_BAR EVNT:Control */
			int pos = 0;
			/*
				Horizontal scrollbar control was operated
			*/
			switch (xdEvent->v.ctl.ci.v.scroll.what) {
			case SC_LINE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
				break;
			case SC_LINE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
				break;
			case SC_PAGE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
				SNAP_DOWN_BY(pos, 1000)
				break;
			case SC_PAGE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
				SNAP_UP_BY(pos, 1000)
				break;
			case SC_THUMB:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			case SC_THUMBTRACK:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			}
			updateScrollField (xdWindow, xdControlId, pos);
			updateNumericTextField (xdWindow, DIM_Z, pos);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END DIM_Z_BAR EVNT:Control */
			}
			break;
		case DIM_X: /* "dx" */
			{
			/* TAG BEGIN DIM_X EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			updateScrollAndText (xdWindow, DIM_X_BAR, DIM_X, FALSE);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END DIM_X EVNT:Control */
			}
			break;
		case DIM_Z: /* "dz" */
			{
			/* TAG BEGIN DIM_Z EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			updateScrollAndText (xdWindow, DIM_Z_BAR, DIM_Z, FALSE);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END DIM_Z EVNT:Control */
			}
			break;
		case DIM_Y: /* "dy" */
			{
			/* TAG BEGIN DIM_Y EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			updateScrollAndText (xdWindow, DIM_Y_BAR, DIM_Y, FALSE);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END DIM_Y EVNT:Control */
			}
			break;
		case VIEW_ORIGIN_X_BAR: /* "Horizontal Scrollbar OX" */
			{
			/* TAG BEGIN VIEW_ORIGIN_X_BAR EVNT:Control */
			int pos = 0;
			/*
				Horizontal scrollbar control was operated
			*/
			switch (xdEvent->v.ctl.ci.v.scroll.what) {
			case SC_LINE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
				break;
			case SC_LINE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
				break;
			case SC_PAGE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
				SNAP_DOWN_BY(pos, 1000)
				break;
			case SC_PAGE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
				SNAP_UP_BY(pos, 1000)
				break;
			case SC_THUMB:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			case SC_THUMBTRACK:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			}
			updateScrollField (xdWindow, xdControlId, pos);
			updateNumericTextField (xdWindow, VIEW_ORIGIN_X, pos);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END VIEW_ORIGIN_X_BAR EVNT:Control */
			}
			break;
		case VIEW_ORIGIN_Y_BAR: /* "Horizontal Scrollbar OY" */
			{
			/* TAG BEGIN VIEW_ORIGIN_Y_BAR EVNT:Control */
			int pos = 0;
			/*
				Horizontal scrollbar control was operated
			*/
			switch (xdEvent->v.ctl.ci.v.scroll.what) {
			case SC_LINE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
				break;
			case SC_LINE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
				break;
			case SC_PAGE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
				SNAP_DOWN_BY(pos, 1000)
				break;
			case SC_PAGE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
				SNAP_UP_BY(pos, 1000)
				break;
			case SC_THUMB:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			case SC_THUMBTRACK:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			}
			updateScrollField (xdWindow, xdControlId, pos);
			updateNumericTextField (xdWindow, VIEW_ORIGIN_Y, pos);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END VIEW_ORIGIN_Y_BAR EVNT:Control */
			}
			break;
		case VIEW_ORIGIN_Z_BAR: /* "Horizontal Scrollbar OZ" */
			{
			/* TAG BEGIN VIEW_ORIGIN_Z_BAR EVNT:Control */
			int pos = 0;
			/*
				Horizontal scrollbar control was operated
			*/
			switch (xdEvent->v.ctl.ci.v.scroll.what) {
			case SC_LINE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
				break;
			case SC_LINE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
				break;
			case SC_PAGE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
				SNAP_DOWN_BY(pos, 1000)
				break;
			case SC_PAGE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
				SNAP_UP_BY(pos, 1000)
				break;
			case SC_THUMB:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			case SC_THUMBTRACK:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			}
			updateScrollField (xdWindow, xdControlId, pos);
			updateNumericTextField (xdWindow, VIEW_ORIGIN_Z, pos);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END VIEW_ORIGIN_Z_BAR EVNT:Control */
			}
			break;
		case VIEW_ORIGIN_X: /* "x" */
			{
			/* TAG BEGIN VIEW_ORIGIN_X EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			updateScrollAndText (xdWindow, VIEW_ORIGIN_X_BAR, VIEW_ORIGIN_X, FALSE);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END VIEW_ORIGIN_X EVNT:Control */
			}
			break;
		case VIEW_ORIGIN_Z: /* "z" */
			{
			/* TAG BEGIN VIEW_ORIGIN_Z EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			updateScrollAndText (xdWindow, VIEW_ORIGIN_Z_BAR, VIEW_ORIGIN_Z, FALSE);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END VIEW_ORIGIN_Z EVNT:Control */
			}
			break;
		case VIEW_ORIGIN_Y: /* "y" */
			{
			/* TAG BEGIN VIEW_ORIGIN_Y EVNT:Control */
			/*
				Edit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			updateScrollAndText (xdWindow, VIEW_ORIGIN_Y_BAR, VIEW_ORIGIN_Y, FALSE);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END VIEW_ORIGIN_Y EVNT:Control */
			}
			break;
		case VIEW_OK: /* "OK" */
			{
			/* TAG BEGIN VIEW_OK EVNT:Control */
						/* ********************************** */
						/* save all the options in the window */
			saveViewOptions (xdWindow);
			xvt_vobj_destroy(xdWindow);
			/* TAG END VIEW_OK EVNT:Control */
			}
			break;
		case VIEW_CANCEL: /* "Cancel" */
			{
			/* TAG BEGIN VIEW_CANCEL EVNT:Control */
			xvt_vobj_destroy(xdWindow);
			/* TAG END VIEW_CANCEL EVNT:Control */
			}
			break;
		case VIEW_HELP: /* "Help..." */
			{
			/* TAG BEGIN VIEW_HELP EVNT:Control */
			displayHelp("blockop.htm");
			/* TAG END VIEW_HELP EVNT:Control */
			}
			break;
		case VIEW_NEW: /* "New..." */
			{
			/* TAG BEGIN VIEW_NEW EVNT:Control */
			char viewName[OBJECT_TEXT_LENGTH];
			BLOCK_VIEW_OPTIONS *viewOptions;
			strcpy (viewName, "New View Name");
			if (xvt_dm_post_string_prompt ("Enter Name of New View", viewName, OBJECT_TEXT_LENGTH))
			{
				viewOptions = getViewOptions();
				newViewOptions (viewName, viewOptions->originX, viewOptions->originY, viewOptions->originZ,
					 viewOptions->lengthX,  viewOptions->lengthY,  viewOptions->lengthZ,
				                 viewOptions->geologyCubeSize, viewOptions->geophysicsCubeSize);
				loadViewOptions (xdWindow);
				update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END VIEW_NEW EVNT:Control */
			}
			break;
		case VIEW_DELETE: /* "Delete" */
			{
			/* TAG BEGIN VIEW_DELETE EVNT:Control */
			if (!deleteViewOptions (getViewOptions()))
			   xvt_dm_post_error ("Error, Cannot delete the last View");
			loadViewOptions (xdWindow);
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END VIEW_DELETE EVNT:Control */
			}
			break;
		case VIEW_CURRENT_LIST: /* "viewlist" */
			{
			/* TAG BEGIN VIEW_CURRENT_LIST EVNT:Control */
			char viewName[OBJECT_TEXT_LENGTH];
			WINDOW viewList;
			saveViewOptions(xdWindow);  /* save what we are looking at */
			viewList = xvt_win_get_ctl (xdWindow, VIEW_CURRENT_LIST);
			xvt_list_get_first_sel (viewList, viewName, OBJECT_TEXT_LENGTH);
			setViewOptions(viewName);
			loadViewOptions(xdWindow);  /* Load the view we are going too */
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			/* TAG END VIEW_CURRENT_LIST EVNT:Control */
			}
			break;
		case VIEW_GEOLOGY_CUBE: /* "geology Cube" */
			{
			/* TAG BEGIN VIEW_GEOLOGY_CUBE EVNT:Control */
			/*
				Listedit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END VIEW_GEOLOGY_CUBE EVNT:Control */
			}
			break;
		case VIEW_GEOPHYSICS_CUBE: /* "geophysics cube" */
			{
			/* TAG BEGIN VIEW_GEOPHYSICS_CUBE EVNT:Control */
			/*
				Listedit control was operated.
			*/
			if (xdEvent->v.ctl.ci.v.edit.focus_change) {
				if (xdEvent->v.ctl.ci.v.edit.active) {
					/*
						focus has entered the control
					*/
				} else {
					/*
						focus has left the control
					*/
				}
			} else {
				/*
					Contents of control were changed
				*/
			update3dPreview ((WINDOW) xvt_vobj_get_data (xdWindow), (OBJECT *) NULL);
			}
			/* TAG END VIEW_GEOPHYSICS_CUBE EVNT:Control */
			}
			break;
		case VIEW_3D_OPTIONS_BUTTON: /* "3D View Options..." */
			{
			/* TAG BEGIN VIEW_3D_OPTIONS_BUTTON EVNT:Control */
			WINDOW win;
			if (!(win = createCenteredWindow(VIEW_OPTIONS_WINDOW, TASK_WIN, EM_ALL, VIEW_OPTIONS_WINDOW_eh, 0L)))
				xvt_dm_post_error("Can't open window");
			/* TAG END VIEW_3D_OPTIONS_BUTTON EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		switch (xdEvent->v.user.id) {
		case -1:
		default:
			break;
		}
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
