/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:35:00 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID FILE_FORMAT_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window FILE_FORMAT_WINDOW ("File Format")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
FILE_FORMAT_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
FILE_FORMAT_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
		addWinToStack (xdWindow);
		loadFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data (xdWindow));
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
		xvt_mem_free ((char *) xvt_vobj_get_data(xdWindow));
		takeWinFromStack (xdWindow);
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		/*
			Window has lost or gained focus.
		*/
		if (xdEvent->v.active) {
			/*
				Window has gained focus
			*/
		} else {
			/*
				Window has lost focus
			*/
		}
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
		         /* *********************************************** */
		         /* make a RETURN key activate the window OK Button */
		      if (xdEvent->v.chr.ch == '\r')
		      {
		         xdEvent->type = E_CONTROL;
		         xdEvent->v.ctl.id = FILE_FORMAT_OK;
		         xvt_win_dispatch_event (xdWindow, xdEvent);
		      }
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		/*
			Horizontal scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		/*
			Vertical scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		/*
			No menubar was associated with this window
		*/
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case FILE_ORDER_X1: /* "1st" */
			{
			/* TAG BEGIN FILE_ORDER_X1 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_X1,
				FILE_ORDER_X1,
				FILE_ORDER_X3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_X1 EVNT:Control */
			}
			break;
		case FILE_ORDER_X2: /* "2nd" */
			{
			/* TAG BEGIN FILE_ORDER_X2 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_X2,
				FILE_ORDER_X1,
				FILE_ORDER_X3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_X2 EVNT:Control */
			}
			break;
		case FILE_ORDER_X3: /* "3rd" */
			{
			/* TAG BEGIN FILE_ORDER_X3 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_X3,
				FILE_ORDER_X1,
				FILE_ORDER_X3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_X3 EVNT:Control */
			}
			break;
		case FILE_ORDER_Y1: /* "1st" */
			{
			/* TAG BEGIN FILE_ORDER_Y1 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_Y1,
				FILE_ORDER_Y1,
				FILE_ORDER_Y3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_Y1 EVNT:Control */
			}
			break;
		case FILE_ORDER_Y2: /* "2nd" */
			{
			/* TAG BEGIN FILE_ORDER_Y2 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_Y2,
				FILE_ORDER_Y1,
				FILE_ORDER_Y3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_Y2 EVNT:Control */
			}
			break;
		case FILE_ORDER_Y3: /* "3rd" */
			{
			/* TAG BEGIN FILE_ORDER_Y3 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_Y3,
				FILE_ORDER_Y1,
				FILE_ORDER_Y3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_Y3 EVNT:Control */
			}
			break;
		case FILE_ORDER_Z1: /* "1st" */
			{
			/* TAG BEGIN FILE_ORDER_Z1 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_Z1,
				FILE_ORDER_Z1,
				FILE_ORDER_Z3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_Z1 EVNT:Control */
			}
			break;
		case FILE_ORDER_Z2: /* "2nd" */
			{
			/* TAG BEGIN FILE_ORDER_Z2 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_Z2,
				FILE_ORDER_Z1,
				FILE_ORDER_Z3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_Z2 EVNT:Control */
			}
			break;
		case FILE_ORDER_Z3: /* "3rd" */
			{
			/* TAG BEGIN FILE_ORDER_Z3 EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_ORDER_Z3,
				FILE_ORDER_Z1,
				FILE_ORDER_Z3);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_ORDER_Z3 EVNT:Control */
			}
			break;
		case FILE_DIR_X_EW: /* "East - West" */
			{
			/* TAG BEGIN FILE_DIR_X_EW EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_DIR_X_EW,
				FILE_DIR_X_EW,
				FILE_DIR_X_WE);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_DIR_X_EW EVNT:Control */
			}
			break;
		case FILE_DIR_X_WE: /* "West - East" */
			{
			/* TAG BEGIN FILE_DIR_X_WE EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_DIR_X_WE,
				FILE_DIR_X_EW,
				FILE_DIR_X_WE);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_DIR_X_WE EVNT:Control */
			}
			break;
		case FILE_DIR_Y_NS: /* "North-South" */
			{
			/* TAG BEGIN FILE_DIR_Y_NS EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_DIR_Y_NS,
				FILE_DIR_Y_NS,
				FILE_DIR_Y_SN);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_DIR_Y_NS EVNT:Control */
			}
			break;
		case FILE_DIR_Y_SN: /* "South-North" */
			{
			/* TAG BEGIN FILE_DIR_Y_SN EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_DIR_Y_SN,
				FILE_DIR_Y_NS,
				FILE_DIR_Y_SN);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_DIR_Y_SN EVNT:Control */
			}
			break;
		case FILE_DIR_Z_UD: /* "Up-Down" */
			{
			/* TAG BEGIN FILE_DIR_Z_UD EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_DIR_Z_UD,
				FILE_DIR_Z_UD,
				FILE_DIR_Z_DU);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_DIR_Z_UD EVNT:Control */
			}
			break;
		case FILE_DIR_Z_DU: /* "Down-Up" */
			{
			/* TAG BEGIN FILE_DIR_Z_DU EVNT:Control */
			xdCheckRadioButton(xdWindow,
				FILE_DIR_Z_DU,
				FILE_DIR_Z_UD,
				FILE_DIR_Z_DU);
			updateFileFormatWindow (xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow));
			/* TAG END FILE_DIR_Z_DU EVNT:Control */
			}
			break;
		case FILE_FORMAT_OK: /* "OK" */
			{
			/* TAG BEGIN FILE_FORMAT_OK EVNT:Control */
						/* ********************************** */
						/* save all the options in the window */
			if (saveFileFormatWindow(xdWindow, (FILE_FORMAT *) xvt_vobj_get_data(xdWindow)))
			   xvt_vobj_destroy(xdWindow);
			else
			{
			   xvt_vobj_set_visible(xdWindow, TRUE);
			}
			/* TAG END FILE_FORMAT_OK EVNT:Control */
			}
			break;
		case FILE_FORMAT_CANCEL: /* "Cancel" */
			{
			/* TAG BEGIN FILE_FORMAT_CANCEL EVNT:Control */
			xvt_vobj_destroy(xdWindow);
			/* TAG END FILE_FORMAT_CANCEL EVNT:Control */
			}
			break;
		case FILE_FORMAT_HELP: /* "Help..." */
			{
			/* TAG BEGIN FILE_FORMAT_HELP EVNT:Control */
			displayHelp("expraw.htm");
			/* TAG END FILE_FORMAT_HELP EVNT:Control */
			}
			break;
		case FILE_PROPERTY: /* "file prop" */
			{
			/* TAG BEGIN FILE_PROPERTY EVNT:Control */
			/* TAG END FILE_PROPERTY EVNT:Control */
			}
			break;
		case FILE_SINGLE_VALUE: /* "Single Value per Line" */
			{
			/* TAG BEGIN FILE_SINGLE_VALUE EVNT:Control */
			WINDOW ctl_win = xvt_win_get_ctl(xdWindow, FILE_SINGLE_VALUE);
			xvt_ctl_set_checked(ctl_win, (BOOLEAN) (!xvt_ctl_is_checked(ctl_win)));
			/* TAG END FILE_SINGLE_VALUE EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		switch (xdEvent->v.user.id) {
		case -1:
		default:
			break;
		}
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
