/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Mon Feb 02 10:23:40 1998
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	This function is the menu event handler for menu TASK_MENUBAR
*/

#define FILE_FORMAT_WINDOW_eh 1
#define OPTIONS_WINDOW_eh 1

void
#if XVT_CC_PROTO
do_TASK_MENUBAR (WINDOW xdWindow, EVENT *xdEvent)
#else
do_TASK_MENUBAR (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	MENU_TAG tag = xdEvent->v.cmd.tag;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (tag) {
	case TASK_MENUBAR_1_144: /* Menu "New History" */
		{
		/* TAG BEGIN TASK_MENUBAR_1_144 EVNT:Select */
		ASK_RESPONSE response;
		
		response = xvt_dm_post_ask("Cancel", "User Defaults", "Factory Defaults",
		             "The Current History will be destroyed. Are you sure you want to start a New History ?");
		
		if (response == RESP_2)  /* User Defaults */
		{
			if (!initProject (TRUE, FALSE))
			   xvt_dm_post_error("Error, Could not create a new History");
		}
		else if (response == RESP_3)
		{
			if (!initProject (TRUE, TRUE))
			   xvt_dm_post_error("Error, Could not create a new History");
		}
		/* TAG END TASK_MENUBAR_1_144 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_33: /* Menu "Read History..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_33 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "his");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read History from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            xvt_fsys_set_dir(&fs.dir);
		            setDefaultDirectory(&(fs.dir));
		            loadHistoryFile(fs.name);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_33 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_82: /* Menu "Save History" */
		{
		/* TAG BEGIN TASK_MENUBAR_1_82 EVNT:Select */
		      FILE_SPEC fs;
		      getCurrentFileName (&fs);
		      
		      if (strlen(fs.name))
		      {
		         /* Save the history file in the current Name */
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "his");
#endif
		         xvt_fsys_set_dir(&fs.dir);
		         saveHistoryFile(fs.name);
		      }
		      else     /* pick it from the directory */
		      {
		         FILE_SPEC fs;
		         strcpy(fs.name,"untitled.his");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "his");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save History as ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            saveHistoryFile(fs.name);
		            {
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_TYPESTR, (long)(&fs)->type );
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_CREATORSTR, (long) "Nody"); 
		            };
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_82 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_26: /* Menu "Save History As..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_26 EVNT:Select */
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		         {
		            addFileExtention (fs.name, ".his");
		            incrementFilename(&fs);
		         }
		         else
		            strcpy (fs.name, "untitled.his");
		      
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "his");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save History as ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            saveHistoryFile(fs.name);
		            {
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_TYPESTR, (long)(&fs)->type );
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_CREATORSTR, (long) "Nody"); 
		            };
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_26 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_98: /* Menu "Save as Defaults" */
		{
		/* TAG BEGIN TASK_MENUBAR_1_98 EVNT:Select */
		      char defaultFile[100];
		      xvt_fsys_set_dir_startup();
		      strcpy (defaultFile, "defaults.his");
		      saveHistoryFile(defaultFile);
		/* TAG END TASK_MENUBAR_1_98 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_128_129: /* Menu "Geological..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_128_129 EVNT:Select */
		      {
		         static FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "PICT");
#else
		         strcpy (fs.type, "bmp");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Picture from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            xvt_fsys_set_dir(&fs.dir);
		            setDefaultDirectory(&(fs.dir));
		            loadTraceImage((OBJECT *) xvt_vobj_get_data(xdWindow), fs.name);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_128_129 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_128_130: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_128_130 EVNT:Select */
		      {
		         extern WINDOW gravityReferenceWindow;
		         ANOMIMAGE_DATA *anomImageData;
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Gravity from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            xvt_fsys_set_dir(&fs.dir);
		            setDefaultDirectory(&(fs.dir));
		            anomImageData = loadAnomImage(fs.name);
		            if (setReferenceImage(anomImageData))
		                                         gravityReferenceWindow = displayAnomaliesImage ("Gravity Reference Image", anomImageData);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_128_130 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_128_131: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_128_131 EVNT:Select */
		      {
		         extern WINDOW magneticsReferenceWindow;
		         ANOMIMAGE_DATA *anomImageData;
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Magnetics from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            xvt_fsys_set_dir(&fs.dir);
		            setDefaultDirectory(&(fs.dir));
		            anomImageData = loadAnomImage(fs.name);
		            if (setReferenceImage(anomImageData))
		                                         magneticsReferenceWindow = displayAnomaliesImage ("Magnetics Reference Image", anomImageData);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_128_131 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_128_101: /* Menu "ERMapper" */
		{
		/* TAG BEGIN TASK_MENUBAR_1_128_101 EVNT:Select */
		      {
		         extern WINDOW magneticsReferenceWindow;
		         extern WINDOW displayERMImage ();
		         ANOMIMAGE_DATA *anomImageData;
		         WINDOW win;
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "ers");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display ERM Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            if (win = displayERMImage (fs.name))
		            {
		                anomImageData = (ANOMIMAGE_DATA *) xvt_vobj_get_data(win);
		                if (setReferenceImage(anomImageData))
		                {
		                    magneticsReferenceWindow = win;
		                    xvt_vobj_set_title (win, "Magnetics Reference Image");
		                }
		            }
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_128_101 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_128_65: /* Menu "Geosoft" */
		{
		/* TAG BEGIN TASK_MENUBAR_1_128_65 EVNT:Select */
		      {
		         extern WINDOW magneticsReferenceWindow;
		         extern WINDOW displayGeosoftImage ();
		         ANOMIMAGE_DATA *anomImageData;
		         WINDOW win;
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "gxf");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Geosoft Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            if (win = displayGeosoftImage (fs.name))
		            {
		                anomImageData = (ANOMIMAGE_DATA *) xvt_vobj_get_data(win);
		                if (setReferenceImage(anomImageData))
		                {
		                    magneticsReferenceWindow = win;
		                    xvt_vobj_set_title (win, "Magnetics Reference Image");
		                }
		            }
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_128_65 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_138_83: /* Menu "Create..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_138_83 EVNT:Select */
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		            addFileExtention (fs.name, ".nmv");
		         else
		            strcpy (fs.name, "untitled.nmv");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "nmv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save Movie as ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            createMovie (&fs);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_138_83 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_138_140: /* Menu "Load..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_138_140 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "nmv");
#else
		         strcpy (fs.type, "nmv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Movie from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            loadMovie(&fs);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_138_140 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_30: /* Menu "Read Picture (BMP)..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_30 EVNT:Select */
		      {
		         static FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "PICT");
#else
		         strcpy (fs.type, "bmp");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Picture from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            loadPictureFile(fs.name);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_30 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_31: /* Menu "Save Picture (BMP)..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_31 EVNT:Select */
		      extern WINDOW lastActiveWindow;
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		         {
#if (XVTWS == MACWS)
		            addFileExtention (fs.name, ".PICT");
#else
		            addFileExtention (fs.name, ".bmp");
#endif
		            incrementFilename(&fs);
		         }
		         else
		         {
#if (XVTWS == MACWS)
		            strcpy (fs.name, "untitled.PICT");
#else
		            strcpy (fs.name, "untitled.bmp");
#endif
		         }
#if (XVTWS == MACWS)
		         strcpy (fs.type, "PICT");
#else
		         strcpy (fs.type, "bmp");
#endif
		      
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save Picture as ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            savePictureFile(lastActiveWindow, fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_31 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_32: /* Menu "Save Orientations..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_32 EVNT:Select */
		      extern WINDOW lastActiveWindow;
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		            addFileExtention (fs.name, ".ori");
		         else
		            strcpy (fs.name, "untitled.ori");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "ori");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save Orientation as ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            saveOrientationFile(lastActiveWindow, fs.name);
		            {
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_TYPESTR, (long)(&fs)->type );
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_CREATORSTR, (long) "XCEL"); 
		            };
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_1_32 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_93: /* Menu "Save Profile..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_93 EVNT:Select */
		      extern WINDOW lastActiveWindow;
		      saveProfileData(lastActiveWindow, NULL);
		/* TAG END TASK_MENUBAR_1_93 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_24: /* Menu "Page Setup..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_24 EVNT:Select */
		      setupPageForPrinter ();
		/* TAG END TASK_MENUBAR_1_24 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_71: /* Menu "Print Page" */
		{
		/* TAG BEGIN TASK_MENUBAR_1_71 EVNT:Select */
		      extern WINDOW lastActiveWindow;
		      printWindow (lastActiveWindow);
		/* TAG END TASK_MENUBAR_1_71 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_74: /* Menu "About Noddy..." */
		{
		/* TAG BEGIN TASK_MENUBAR_1_74 EVNT:Select */
		      if (!xvt_dlg_create_res(WD_MODAL, DLG_126, EM_ALL, DLG_126_eh, 0L))
		         xvt_dm_post_error("Can't open dialog");
		/* TAG END TASK_MENUBAR_1_74 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_1_23: /* Menu "Exit" */
		{
		/* TAG BEGIN TASK_MENUBAR_1_23 EVNT:Select */
		      if (is_quit_OK())
		      {
		         xvt_app_destroy();
		      }
		/* TAG END TASK_MENUBAR_1_23 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_9: /* Menu "Undo" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_9 EVNT:Select */
		         /* undo the last action */
		      undoChanges (getEventDrawingWindow ());
		/* TAG END TASK_MENUBAR_2_9 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_10: /* Menu "Cut" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_10 EVNT:Select */
		         /* copy selection to clipboard and then delete them */
		      cutSelectedObjects (getEventDrawingWindow ());
		/* TAG END TASK_MENUBAR_2_10 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_75: /* Menu "Copy" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_75 EVNT:Select */
		         /* copy selection to clipboard */
		      copySelectedObjects (getEventDrawingWindow ());
		/* TAG END TASK_MENUBAR_2_75 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_8: /* Menu "Paste" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_8 EVNT:Select */
		         /* copy selection from the clipboard and re-insert them */
		      pasteObjects (getEventDrawingWindow ());
		/* TAG END TASK_MENUBAR_2_8 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_15: /* Menu "Clear" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_15 EVNT:Select */
		            /* delete the selected objects */
		      deleteSelectedObjects (getEventDrawingWindow (), FALSE);
		/* TAG END TASK_MENUBAR_2_15 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_20: /* Menu "Duplicate" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_20 EVNT:Select */
		         /* copy selection to clipboard and then paste it */
		      duplicateSelectedObjects (getEventDrawingWindow ());
		/* TAG END TASK_MENUBAR_2_20 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_21: /* Menu "Select All" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_21 EVNT:Select */
		      selectAllObjects ();
		/* TAG END TASK_MENUBAR_2_21 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_61: /* Menu "Tidy Window" */
		{
		/* TAG BEGIN TASK_MENUBAR_2_61 EVNT:Select */
		         /* put the objects in there closest representation */
		      tidyObjects (getEventDrawingWindow ());
		/* TAG END TASK_MENUBAR_2_61 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_148: /* Menu "Project Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_148 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) PROJECT_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_148 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_150: /* Menu "Block Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_150 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) BLOCK_VIEW_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_150 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_151: /* Menu "Movie Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_151 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) MOVIE_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_151 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_46: /* Menu "Geology Display Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_46 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) GEOLOGY_DISPLAY_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_46 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_152: /* Menu "Geology Section/Borehole Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_152 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) BOREHOLE_SECTION_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_152 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_153: /* Menu "Geology Volume/Surface Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_153 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) VOLUME_SURFACE_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_153 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_145: /* Menu "Geophysics Calculation Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_145 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) GEOPHYSICS_CALC_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_145 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_146: /* Menu "Geophysics Survey Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_146 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) GEOPHYSICS_SURVEY_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_146 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_147: /* Menu "Geophysics Display Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_147 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) GEOPHYSICS_DISPLAY_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_147 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_2_149: /* Menu "Window Options..." */
		{
		/* TAG BEGIN TASK_MENUBAR_2_149 EVNT:Select */
		WINDOW win;
		if (!(win = createCenteredWindow(OPTIONS_WINDOW, TASK_WIN, EM_ALL, OPTIONS_WINDOW_eh, (long) WINDOW_POSITION_OP)))
		   xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_2_149 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_27: /* Menu "Block Diagram" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_27 EVNT:Select */
		      updateBlockDiagram (NULL_WIN);
		/* TAG END TASK_MENUBAR_4_27 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_28_53: /* Menu "Solid Colours..." */
		{
		/* TAG BEGIN TASK_MENUBAR_4_28_53 EVNT:Select */
		      BLOCK_VIEW_OPTIONS *blockView = getViewOptions();
		      BLOCK_SURFACE_DATA *surface;
		      if (surface = (BLOCK_SURFACE_DATA *) xvt_mem_zalloc (sizeof(BLOCK_SURFACE_DATA)))
		      {
		         surface->xStart = blockView->originX;
		         surface->xEnd = blockView->originX + blockView->lengthX;
		         surface->yStart = blockView->originY;
		         surface->yEnd = blockView->originY + blockView->lengthY;
		         surface->zStart = blockView->originZ;
		         surface->zEnd = blockView->originZ;
		      
		         updateSection (TRUE, surface);
		         xvt_mem_free ((char *) surface);
		      }
		/* TAG END TASK_MENUBAR_4_28_53 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_28_54: /* Menu "Lines..." */
		{
		/* TAG BEGIN TASK_MENUBAR_4_28_54 EVNT:Select */
		      BLOCK_VIEW_OPTIONS *blockView = getViewOptions();
		      BLOCK_SURFACE_DATA *surface;
		      if (surface = (BLOCK_SURFACE_DATA *) xvt_mem_zalloc (sizeof(BLOCK_SURFACE_DATA)))
		      {
		         surface->xStart = blockView->originX;
		         surface->xEnd = blockView->originX + blockView->lengthX;
		         surface->yStart = blockView->originY;
		         surface->yEnd = blockView->originY + blockView->lengthY;
		         surface->zStart = blockView->originZ;
		         surface->zEnd = blockView->originZ;
		      
		         updateSection (FALSE, surface);
		         xvt_mem_free ((char *) surface);
		      }
		/* TAG END TASK_MENUBAR_4_28_54 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_29: /* Menu "Topo Map" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_29 EVNT:Select */
		      updateTopographyMap ();
		/* TAG END TASK_MENUBAR_4_29 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_47_55: /* Menu "Solid Colours..." */
		{
		/* TAG BEGIN TASK_MENUBAR_4_47_55 EVNT:Select */
		extern GEOLOGY_OPTIONS geologyOptions;
		BLOCK_VIEW_OPTIONS *blockView = getViewOptions();
		BLOCK_SURFACE_DATA *surface;
		double dx, dy;
		if (surface = (BLOCK_SURFACE_DATA *) xvt_mem_zalloc (sizeof(BLOCK_SURFACE_DATA)))
		{
		   dx = sin(geologyOptions.sectionDecl*0.01745329)
		                                 *geologyOptions.sectionLength;
		   dy = cos(geologyOptions.sectionDecl*0.01745329)
		                                 *geologyOptions.sectionLength;
		
		   surface->xStart = geologyOptions.sectionX;
		   surface->xEnd = geologyOptions.sectionX + dx;
		   surface->yStart = geologyOptions.sectionY;
		   surface->yEnd = geologyOptions.sectionY + dy;
		   surface->zStart = blockView->originZ - blockView->lengthZ;
		   surface->zEnd = blockView->originZ;
		
		   updateSection (TRUE, surface);
		   xvt_mem_free ((char *) surface);
		}
		/* TAG END TASK_MENUBAR_4_47_55 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_47_56: /* Menu "Lines..." */
		{
		/* TAG BEGIN TASK_MENUBAR_4_47_56 EVNT:Select */
		extern GEOLOGY_OPTIONS geologyOptions;
		BLOCK_VIEW_OPTIONS *blockView = getViewOptions();
		BLOCK_SURFACE_DATA *surface;
		double dx, dy;
		if (surface = (BLOCK_SURFACE_DATA *) xvt_mem_zalloc (sizeof(BLOCK_SURFACE_DATA)))
		{
		   dx = sin(geologyOptions.sectionDecl*0.01745329)
		                                 *geologyOptions.sectionLength;
		   dy = cos(geologyOptions.sectionDecl*0.01745329)
		                                 *geologyOptions.sectionLength;
		
		   surface->xStart = geologyOptions.sectionX;
		   surface->xEnd = geologyOptions.sectionX + dx;
		   surface->yStart = geologyOptions.sectionY;
		   surface->yEnd = geologyOptions.sectionY + dy;
		   surface->zStart = blockView->originZ - blockView->lengthZ;
		   surface->zEnd = blockView->originZ;
		      
		   updateSection (FALSE, surface);
		   xvt_mem_free ((char *) surface);
		}
		/* TAG END TASK_MENUBAR_4_47_56 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_70: /* Menu "Stratigraphic Column" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_70 EVNT:Select */
		updateStratColumns ();
		/* TAG END TASK_MENUBAR_4_70 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_48_111_113: /* Menu "3D" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_48_111_113 EVNT:Select */
		extern GEOLOGY_OPTIONS geologyOptions;
		int numPoints;
		double **xyzPoints;
		if (xyzPoints = (double **) generateBoreholePoints (geologyOptions.boreholeX,
		                                geologyOptions.boreholeY, geologyOptions.boreholeZ,
		                                geologyOptions.boreholeDecl, geologyOptions.boreholeDip, 
		                                geologyOptions.boreholeLength,
												  (double) (getViewOptions()->geologyCubeSize)/2.0, &numPoints))
		   updateBorehole (xyzPoints, numPoints, TRUE);
		/* TAG END TASK_MENUBAR_4_48_111_113 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_48_111_114: /* Menu "Schematic" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_48_111_114 EVNT:Select */
		extern GEOLOGY_OPTIONS geologyOptions;
		int numPoints;
		double **xyzPoints;
		if (xyzPoints = (double **) generateBoreholePoints (geologyOptions.boreholeX,
		                                geologyOptions.boreholeY, geologyOptions.boreholeZ,
		                                geologyOptions.boreholeDecl, geologyOptions.boreholeDip, 
		                                geologyOptions.boreholeLength,
												  (double) (getViewOptions()->geologyCubeSize)/2.0, &numPoints))
		   updateBorehole (xyzPoints, numPoints, FALSE);
		/* TAG END TASK_MENUBAR_4_48_111_114 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_48_112_115: /* Menu "3D..." */
		{
		/* TAG BEGIN TASK_MENUBAR_4_48_112_115 EVNT:Select */
		      {
		         FILE_SPEC fileinfo;
#if (XVTWS == MACWS)
		         strcpy (fileinfo.type, "TEXT");
#else
		         strcpy (fileinfo.type, "xyz");
#endif
		         getDefaultDirectory(&(fileinfo.dir));
		         switch (xvt_dm_post_file_open(&fileinfo, "Read Borehole from ...")) {
		         case FL_OK:
		            if (strlen(fileinfo.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fileinfo.dir));
		            importBoreholePoints (&fileinfo, TRUE);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_4_48_112_115 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_48_112_116: /* Menu "Schematic..." */
		{
		/* TAG BEGIN TASK_MENUBAR_4_48_112_116 EVNT:Select */
		      {
		         FILE_SPEC fileinfo;
#if (XVTWS == MACWS)
		         strcpy (fileinfo.type, "TEXT");
#else
		         strcpy (fileinfo.type, "xyz");
#endif
		         getDefaultDirectory(&(fileinfo.dir));
		         switch (xvt_dm_post_file_open(&fileinfo, "Read Borehole from ...")) {
		         case FL_OK:
		            if (strlen(fileinfo.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fileinfo.dir));
		            importBoreholePoints (&fileinfo, FALSE);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_4_48_112_116 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_49: /* Menu "3D Topo" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_49 EVNT:Select */
		      update3dTopographyMap ();
		/* TAG END TASK_MENUBAR_4_49 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_50: /* Menu "3D Triangulation" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_50 EVNT:Select */
		      update3dStratigraphy ();
		/* TAG END TASK_MENUBAR_4_50 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_4_69: /* Menu "Plot Orientations" */
		{
		/* TAG BEGIN TASK_MENUBAR_4_69 EVNT:Select */
		      extern WINDOW lastActiveWindow;
		      plotOrientations (lastActiveWindow);
		/* TAG END TASK_MENUBAR_4_69 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_11_43: /* Menu "Anomalies..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_11_43 EVNT:Select */
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		            addFileExtention (fs.name, ".mag");
		         else
		            strcpy(fs.name, "untitled.mag");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save as:")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calculateAnomalies (fs.name, ANOM, TRUE);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_11_43 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_11_44: /* Menu "Block and Anomalies..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_11_44 EVNT:Select */
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		            addFileExtention (fs.name, ".mag");
		         else
		            strcpy(fs.name, "untitled.mag");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save as:")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calculateAnomalies (fs.name, BLOCK_AND_ANOM, TRUE);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_11_44 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_11_45: /* Menu "Anomalies from Block..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_11_45 EVNT:Select */
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		            addFileExtention (fs.name, ".mag");
		         else
		            strcpy(fs.name, "untitled.mag");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save as:")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calculateAnomalies (fs.name, ANOM_FROM_BLOCK, TRUE);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_11_45 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_11_117_118: /* Menu "Generated" */
		{
		/* TAG BEGIN TASK_MENUBAR_5_11_117_118 EVNT:Select */
		      extern GEOLOGY_OPTIONS geologyOptions;
		      extern GEOPHYSICS_OPTIONS geophysicsOptions;
		      int numPoints, point;
		      double **xyzPoints;
		      double minX, minY, minZ, maxX, maxY, maxZ;
		      BLOCK_VIEW_OPTIONS *viewOptions = getViewOptions (), blockView;
		      GEOPHYSICS_OPTIONS options;
		      FILE_SPEC fs;
		      if (xyzPoints = (double **) generateBoreholePoints (geologyOptions.boreholeX, geologyOptions.boreholeY, geologyOptions.boreholeZ,
		                                                              geologyOptions.boreholeDecl, geologyOptions.boreholeDip, 
		                                                              geologyOptions.boreholeLength, viewOptions->geophysicsCubeSize,
		                                                              &numPoints))
		      {
		      /*
		         minX = maxX = xyzPoints[0][0];
		         minY = maxY = xyzPoints[0][1];
		         minZ = maxZ = xyzPoints[0][2];
		      */
		         minX = viewOptions->originX;  /* Use the default block as the default bounds */
		         minY = viewOptions->originY;
		         minZ = viewOptions->originZ - viewOptions->lengthZ;
		         maxX = viewOptions->originX + viewOptions->lengthX;
		         maxY = viewOptions->originY + viewOptions->lengthY;
		         maxZ = viewOptions->originZ;
		         for (point = 0; point < numPoints; point++)
		         {
		            if (xyzPoints[point][0] < minX)
		               minX = xyzPoints[point][0];
		            else if (xyzPoints[point][0] > maxX)
		               maxX = xyzPoints[point][0];
		      
		            if (xyzPoints[point][1] < minY)
		               minY = xyzPoints[point][1];
		            else if (xyzPoints[point][1] > maxY)
		               maxY = xyzPoints[point][1];
		      
		            if (xyzPoints[point][2] < minZ)
		               minZ = xyzPoints[point][2];
		            else if (xyzPoints[point][2] > maxZ)
		               maxZ = xyzPoints[point][2];
		         }
		         memcpy (&blockView, viewOptions, sizeof(BLOCK_VIEW_OPTIONS));
		         blockView.originX = minX - blockView.geologyCubeSize*2;
		         blockView.originY = minY - blockView.geologyCubeSize*2;
		         /* blockView.originZ = maxZ + blockView.geologyCubeSize*2; */
		         blockView.lengthX = (maxX - minX) + blockView.geologyCubeSize*4;
		         blockView.lengthY = (maxY - minY) + blockView.geologyCubeSize*4;
		         /* blockView.lengthZ = (maxZ - minZ) + blockView.geologyCubeSize*4; */
		         memcpy (&options, &geophysicsOptions, sizeof(GEOPHYSICS_OPTIONS));
		         if (options.calculationMethod == SPATIAL)   /* Spatial cannot do XYZ */
		            options.calculationMethod = SPECTRAL;
		      
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		            addFileExtention (fs.name, ".geo");
		         else
		            strcpy(fs.name, "untitled.geo");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "geo");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save Borehole As:")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            doGeophysics (XYZ_ANOM, &blockView, &options, fs.name, NULL, xyzPoints, numPoints, NULL, NULL, NULL);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      
		         finishLongJob ();
		         destroy2DArray((char **) xyzPoints, numPoints, 3);
		      }
		/* TAG END TASK_MENUBAR_5_11_117_118 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_11_117_119: /* Menu "Imported..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_11_117_119 EVNT:Select */
		      {
		         XYZ_IMPORT *xyzImport;
		         WINDOW win;
		         FILE_SPEC fs;
		      
		         if (!(xyzImport = (XYZ_IMPORT *) xvt_mem_zalloc(sizeof(XYZ_IMPORT))))
		            break;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "geo");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read XYZ's from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            memcpy (&(xyzImport->fileSpec), &fs, sizeof(FILE_SPEC));
		            xyzImport->type = XYZ_GEO_IMPORT;
		            if (!(win = createCenteredWindow(XYZ_CONVERT_WINDOW, TASK_WIN, EM_ALL, XYZ_CONVERT_WINDOW_eh, (long) xyzImport)))
		            {
		               xvt_mem_free ((char *) xyzImport);
		               xvt_dm_post_error("Can't open window");
		            }
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_11_117_119 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_11_90_91: /* Menu "Import From File..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_11_90_91 EVNT:Select */
		      {
		         XYZ_IMPORT *xyzImport;
		         WINDOW win;
		         FILE_SPEC fs;
		      
		         if (!(xyzImport = (XYZ_IMPORT *) xvt_mem_zalloc(sizeof(XYZ_IMPORT))))
		            break;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "geo");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read XYZ's from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            memcpy (&(xyzImport->fileSpec), &fs, sizeof(FILE_SPEC));
		            xyzImport->type = XYZ_GEO_IMPORT;
		            if (!(win = createCenteredWindow(XYZ_CONVERT_WINDOW, TASK_WIN, EM_ALL, XYZ_CONVERT_WINDOW_eh, (long) xyzImport)))
		            {
		               xvt_mem_free ((char *) xyzImport);
		               xvt_dm_post_error("Can't open window");
		            }
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_11_90_91 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_11_90_92: /* Menu "Generate..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_11_90_92 EVNT:Select */
		      WINDOW win;
		      if (!(win = createCenteredWindow(XYZ_GENERATION_WINDOW, TASK_WIN, EM_ALL, XYZ_GENERATION_WINDOW_eh, 0L)))
		         xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_5_11_90_92 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_120_121_123: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_120_121_123 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "First Derivative from...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calcVertDerivImage(fs.name, 1);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_120_121_123 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_120_121_124: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_120_121_124 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "First Derivative from...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calcVertDerivImage(fs.name, 1);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_120_121_124 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_120_122_125: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_120_122_125 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Second Derivative from...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calcVertDerivImage(fs.name, 2);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_120_122_125 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_120_122_126: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_120_122_126 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Second Derivative from...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calcVertDerivImage(fs.name, 2);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_120_122_126 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_134_135: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_134_135 EVNT:Select */
		      {
		         extern ANOMIMAGE_DATA *gravityReferenceData;
		         ANOMIMAGE_DATA *anomImageData, *result;
		         FILE_SPEC fs;
		      
		         if (!gravityReferenceData)
		         {
		            xvt_dm_post_error ("Error, load a Gravity Reference Image First.");
		            break;
		         }
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Gravity from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            if (!(anomImageData = loadAnomImage(fs.name)))
		               break;
		            if (result = (ANOMIMAGE_DATA *) xvt_mem_zalloc (sizeof(ANOMIMAGE_DATA)))
		            {
		               if (calcImageDifference(anomImageData, gravityReferenceData, result))
		                  displayAnomaliesImage ("Difference with Reference", result);
		               else
		               {
		                  destroy2DArray ((char **) result->imageData,
		                  result->dataYSize, result->dataXSize);
		                  xvt_mem_free ((char *) result);
		               }
		            }
		            destroy2DArray ((char **) anomImageData->imageData,
		                  anomImageData->dataYSize, anomImageData->dataXSize);
		            xvt_mem_free ((char *) anomImageData);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_134_135 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_134_136: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_134_136 EVNT:Select */
		      {
		         extern ANOMIMAGE_DATA *magneticsReferenceData;
		         ANOMIMAGE_DATA *anomImageData, *result;
		         FILE_SPEC fs;
		      
		         if (!magneticsReferenceData)
		         {
		            xvt_dm_post_error ("Error, load a Magnetics Reference Image First.");
		            break;
		         }
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Magnetics from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            if (!(anomImageData = loadAnomImage(fs.name)))
		               break;
		            if (result = (ANOMIMAGE_DATA *) xvt_mem_zalloc (sizeof(ANOMIMAGE_DATA)))
		            {
		               if (calcImageDifference(anomImageData, magneticsReferenceData, result))
		                  displayAnomaliesImage ("Difference with Reference", result);
		               else
		               {
		                  destroy2DArray ((char **) result->imageData,
		                  result->dataYSize, result->dataXSize);
		                  xvt_mem_free ((char *) result);
		               }
		            }
		            destroy2DArray ((char **) anomImageData->imageData,
		                  anomImageData->dataYSize, anomImageData->dataXSize);
		            xvt_mem_free ((char *) anomImageData);
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_134_136 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_12_63: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_12_63 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            displayAnomaliesImage (fs.name, NULL);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_12_63 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_12_64: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_12_64 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            displayAnomaliesImage (fs.name, NULL);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_12_64 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_12_102: /* Menu "Magnetics X..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_12_102 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mgx");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            displayAnomaliesImage (fs.name, NULL);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_12_102 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_12_103: /* Menu "Magnetics Y..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_12_103 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mgy");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            displayAnomaliesImage (fs.name, NULL);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_12_103 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_12_104: /* Menu "Magnetics Z..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_12_104 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mgz");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            displayAnomaliesImage (fs.name, NULL);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_12_104 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_12_13: /* Menu "ERMapper" */
		{
		/* TAG BEGIN TASK_MENUBAR_5_12_13 EVNT:Select */
		      {
		         extern WINDOW displayERMImage ();
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "ers");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display ERM Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            displayERMImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_12_13 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_12_19: /* Menu "Geosoft" */
		{
		/* TAG BEGIN TASK_MENUBAR_5_12_19 EVNT:Select */
		      {
		         extern WINDOW displayGeosoftImage ();
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "gxf");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Geosoft Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            displayGeosoftImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_12_19 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_14_67: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_14_67 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Profile...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            loadProfileImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_14_67 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_5_14_68: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_5_14_68 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Display Profile...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            loadProfileImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_5_14_68 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_86_139: /* Menu "DXF..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_86_139 EVNT:Select */
		      {
		         WINDOW win;
		         FILE_SPEC fs, *dxfFile;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "DXF");
#else
		         strcpy (fs.type, "dxf");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "DXF File to convert...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            if (dxfFile = (FILE_SPEC *) xvt_mem_zalloc(sizeof(FILE_SPEC)))
		            {
		               memcpy (dxfFile, &fs, sizeof (FILE_SPEC));
		               if (!(win = createCenteredWindow(DXF_IMPORT_WINDOW, TASK_WIN, EM_ALL, DXF_IMPORT_WINDOW_eh, (long) dxfFile)))
		                  xvt_dm_post_error("Can't open window");
		            }
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_85_86_139 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_86_87: /* Menu "Vulcan..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_86_87 EVNT:Select */
		      WINDOW win;
		      if (!(win = createCenteredWindow(BLOCK_CONVERT_WINDOW, TASK_WIN, EM_ALL, BLOCK_CONVERT_WINDOW_eh, 1L)))
		         xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_85_86_87 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_86_89: /* Menu "Old Noddy Block..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_86_89 EVNT:Select */
		      WINDOW win;
		      if (!(win = createCenteredWindow(BLOCK_CONVERT_WINDOW, TASK_WIN, EM_ALL, BLOCK_CONVERT_WINDOW_eh, 2L)))
		         xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_85_86_89 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_133_132: /* Menu "ASCII..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_133_132 EVNT:Select */
		      WINDOW win;
		      if (!(win = createCenteredWindow(ASCII_IMAGE_OPTIONS, TASK_WIN, EM_ALL, ASCII_IMAGE_OPTIONS_eh, 0L)))
		         xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_85_133_132 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_133_127: /* Menu "Column..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_133_127 EVNT:Select */
		      {
		         XYZ_IMPORT *xyzImport;
		         WINDOW win;
		         FILE_SPEC fs;
		      
		         if (!(xyzImport = (XYZ_IMPORT *) xvt_mem_zalloc(sizeof(XYZ_IMPORT))))
		            break;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "geo");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Read Column Data from ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            memcpy (&(xyzImport->fileSpec), &fs, sizeof(FILE_SPEC));
		            xyzImport->type = XYZ_IMAGE_IMPORT;
		            if (!(win = createCenteredWindow(XYZ_CONVERT_WINDOW, TASK_WIN, EM_ALL, XYZ_CONVERT_WINDOW_eh, (long) xyzImport)))
		            {
		               xvt_mem_free ((char *) xyzImport);
		               xvt_dm_post_error("Can't open window");
		            }
		            break;
		         case FL_BAD:
		            xvt_dm_post_error("Error getting file name.");
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_85_133_127 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_141_72: /* Menu "Noddy Block Model..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_141_72 EVNT:Select */
		      {
		         FILE_SPEC fs;
		         getCurrentFileName (&fs);
		         if (strlen(fs.name))
		            addFileExtention (fs.name, ".g00");
		         else
		            strcpy (fs.name, "untitled.g00");
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "g00");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Save Block Model as ...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            calculateAnomalies (fs.name, BLOCK_ONLY, TRUE);
		            {
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_TYPESTR, (long)(&fs)->type );
		             xvt_fsys_set_file_attr(&fs, XVT_FILE_ATTR_CREATORSTR, (long) "Nody");
		             };
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_85_141_72 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_141_73: /* Menu "Raw Voxel Model..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_141_73 EVNT:Select */
		WINDOW win;
		FILE_FORMAT *fileFormat;
		if (!(fileFormat = (FILE_FORMAT *) xvt_mem_zalloc (sizeof(FILE_FORMAT))))
		{
		   xvt_dm_post_error("Error, Not enough memory to save a raw block model");
		   break;
		}
		fileFormat->type = DICER_BLOCK_FILE;
		fileFormat->access = OUTPUT;
		fileFormat->property = ROCK_PROP;
		fileFormat->xOrder = FIRST;
		fileFormat->yOrder = SECOND;
		fileFormat->zOrder = THIRD;
		fileFormat->xDirection = WEST_EAST;
		fileFormat->yDirection = SOUTH_NORTH;
		fileFormat->zDirection = DOWN_UP;
		if (!(win = createCenteredWindow(FILE_FORMAT_WINDOW, TASK_WIN, EM_ALL, FILE_FORMAT_WINDOW_eh, (long) fileFormat)))
		{
		   xvt_dm_post_error("Can't open window");
		   xvt_mem_free ((char *) fileFormat);
		}
		/* TAG END TASK_MENUBAR_85_141_73 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_141_22: /* Menu "Tabulated Columns..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_141_22 EVNT:Select */
		WINDOW win;
		FILE_FORMAT *fileFormat;
		if (!(fileFormat = (FILE_FORMAT *) xvt_mem_zalloc (sizeof(FILE_FORMAT))))
		{
		   xvt_dm_post_error("Error, Not enough memory to save a dicer block model");
		   break;
		}
		fileFormat->type = TABULATED_COL_BLOCK_FILE;
		fileFormat->access = OUTPUT;
		fileFormat->property = ROCK_PROP;
		fileFormat->xOrder = FIRST;
		fileFormat->yOrder = SECOND;
		fileFormat->zOrder = THIRD;
		fileFormat->xDirection = WEST_EAST;
		fileFormat->yDirection = SOUTH_NORTH;
		fileFormat->zDirection = DOWN_UP;
		if (!(win = createCenteredWindow(FILE_FORMAT_WINDOW, TASK_WIN, EM_ALL, FILE_FORMAT_WINDOW_eh, (long) fileFormat)))
		{
		   xvt_dm_post_error("Can't open window");
		   xvt_mem_free ((char *) fileFormat);
		}
		/* TAG END TASK_MENUBAR_85_141_22 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_141_105: /* Menu "DXF - 3D Faces" */
		{
		/* TAG BEGIN TASK_MENUBAR_85_141_105 EVNT:Select */
		extern THREED_VIEW_OPTIONS threedViewOptions;
		int fillType;
		fillType = (int) threedViewOptions.fillType;
		threedViewOptions.fillType = DXF_FILE_FILL_3DFACE;
		update3dStratigraphy ();
		threedViewOptions.fillType = fillType;
		/* TAG END TASK_MENUBAR_85_141_105 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_141_106: /* Menu "DXF - Polylines" */
		{
		/* TAG BEGIN TASK_MENUBAR_85_141_106 EVNT:Select */
		extern THREED_VIEW_OPTIONS threedViewOptions;
		int fillType;
		fillType = (int) threedViewOptions.fillType;
		threedViewOptions.fillType = DXF_FILE_FILL_POLYLINE;
		update3dStratigraphy ();
		threedViewOptions.fillType = fillType;
		/* TAG END TASK_MENUBAR_85_141_106 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_141_107: /* Menu "Vulcan" */
		{
		/* TAG BEGIN TASK_MENUBAR_85_141_107 EVNT:Select */
		extern THREED_VIEW_OPTIONS threedViewOptions;
		int fillType;
		fillType = (int) threedViewOptions.fillType;
		threedViewOptions.fillType = VULCAN_FILE_FILL;
		update3dStratigraphy ();
		threedViewOptions.fillType = fillType;
		/* TAG END TASK_MENUBAR_85_141_107 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_141_143: /* Menu "Fractal Graphics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_141_143 EVNT:Select */
		{
		         BLOCK_VIEW_OPTIONS *blockView = (BLOCK_VIEW_OPTIONS *) getViewOptions();
		         int nx, ny, nz;
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "fgr");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_save(&fs, "Fractal Graphics Block...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            writeFractalGraphicsBlock (&fs, blockView->originX, blockView->originY, blockView->originZ,
		                                                                blockView->geologyCubeSize,
		                                                                (int) floor(blockView->lengthX/blockView->geologyCubeSize),
		                                                                (int) floor(blockView->lengthY/blockView->geologyCubeSize),
		                                                                (int) floor(blockView->lengthZ/blockView->geologyCubeSize));
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		}
		/* TAG END TASK_MENUBAR_85_141_143 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_142_94_95: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_142_94_95 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Convert Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            convertToERMImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_85_142_94_95 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_142_94_96: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_142_94_96 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Convert Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            convertToERMImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_85_142_94_96 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_142_94_100: /* Menu "Line Map..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_142_94_100 EVNT:Select */
		      convertToERMImage ("");
		/* TAG END TASK_MENUBAR_85_142_94_100 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_142_108_109: /* Menu "Gravity..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_142_108_109 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "grv");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Convert Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            convertToGeosoftImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_85_142_108_109 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_142_108_110: /* Menu "Magnetics..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_142_108_110 EVNT:Select */
		      {
		         FILE_SPEC fs;
#if (XVTWS == MACWS)
		         strcpy (fs.type, "TEXT");
#else
		         strcpy (fs.type, "mag");
#endif
		         getDefaultDirectory(&(fs.dir));
		         switch (xvt_dm_post_file_open(&fs, "Convert Image...")) {
		         case FL_OK:
		            if (strlen(fs.name) == 0)
		            {
		               xvt_dm_post_error ("Error, No file Specified");
		               break;
		            }
		            setDefaultDirectory(&(fs.dir));
		            xvt_fsys_set_dir(&fs.dir);
		            convertToGeosoftImage (fs.name);
		            break;
		         case FL_BAD:
		            break;
		         case FL_CANCEL:
		            break;
		         }
		      }
		/* TAG END TASK_MENUBAR_85_142_108_110 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_85_99: /* Menu "Edit Rock Database..." */
		{
		/* TAG BEGIN TASK_MENUBAR_85_99 EVNT:Select */
		      WINDOW win;
		      if (!(win = createCenteredWindow(ROCK_DATABASE_WIN, TASK_WIN, EM_ALL, ROCK_DATABASE_WIN_eh, 0L)))
		         xvt_dm_post_error("Can't open window");
		/* TAG END TASK_MENUBAR_85_99 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_77_79: /* Menu "Cascade" */
		{
		/* TAG BEGIN TASK_MENUBAR_77_79 EVNT:Select */
		      cascadeWindows ();
		/* TAG END TASK_MENUBAR_77_79 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_77_78: /* Menu "Tile" */
		{
		/* TAG BEGIN TASK_MENUBAR_77_78 EVNT:Select */
		      tileWindows ();
		/* TAG END TASK_MENUBAR_77_78 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_77_84: /* Menu "Default Size" */
		{
		/* TAG BEGIN TASK_MENUBAR_77_84 EVNT:Select */
		      extern WINDOW lastActiveWindow;
		      restoreWindowSize (lastActiveWindow);
		/* TAG END TASK_MENUBAR_77_84 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_77_80: /* Menu "Remove All" */
		{
		/* TAG BEGIN TASK_MENUBAR_77_80 EVNT:Select */
		      removeAllWindows ();
		/* TAG END TASK_MENUBAR_77_80 EVNT:Select */
		}
		break;
	case TASK_MENUBAR_77_18: /* Menu "Legend" */
		{
		/* TAG BEGIN TASK_MENUBAR_77_18 EVNT:Select */
		extern int toggleLegendWindowDisplay ();
		toggleLegendWindowDisplay ();
		/* TAG END TASK_MENUBAR_77_18 EVNT:Select */
		}
		break;
	default:
		{
		/* TAG BEGIN SPCL:Default */
		      raiseWindow(tag-TASK_MENUBAR_77_18-2001);
		/* TAG END SPCL:Default */
		}
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
	/* TAG END SPCL:Bottom */
}
