/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:34:59 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* Custom control header files */
#include "graph.h"

/* 
	Information about the window
*/
#define WIN_RES_ID PROFILE_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC

static char *PROFILE_WINDOW_CUSTOM_50_props[] = {
	/* title */
	"Custom Control 50",
	NULL
};

static int PROFILE_WINDOW_CUSTOM_50_num_props = 1;
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window PROFILE_WINDOW ("Profile")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
PROFILE_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
PROFILE_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	xvtcm_parent_event(xdWindow, xdEvent);

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/

		/*
			Create the custom controls.
		*/

		graph_create(PROFILE_WINDOW_CUSTOM_50, 4, 4, 404, 204, 
			PROFILE_WINDOW_CUSTOM_50_num_props, PROFILE_WINDOW_CUSTOM_50_props,
			xdWindow, WIN_RES_ID, WIN_FLAGS, WIN_CLASS);
		{
		/* TAG BEGIN EVNT:Create */
			/* put this window in the created heirachy */
		addWinToStack (xdWindow);
					/* *********************************** */
					/* setup all the options in the window */
		loadProfileOptions (xdWindow, (OBJECT *) xvt_vobj_get_data (xdWindow));
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
			/* take this window out of the created heirachy */
		takeWinFromStack (xdWindow);
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		/*
			Window has lost or gained focus.
		*/
		if (xdEvent->v.active) {
			/*
				Window has gained focus
			*/
		} else {
			/*
				Window has lost focus
			*/
		}
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
			/* *********************************************** */
			/* make a RETURN key activate the window OK Button */
		if (xdEvent->v.chr.ch == '\r')
		{
		   xdEvent->type = E_CONTROL;
		   xdEvent->v.ctl.id = PROFILE_WINDOW_PUSHBUTTON_37;
		   xvt_win_dispatch_event (xdWindow, xdEvent);
		}
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		/*
			Horizontal scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		/*
			Vertical scrollbar on frame was operated
		*/
		switch (xdEvent->v.scroll.what) {
		case SC_LINE_UP:
			break;
		case SC_LINE_DOWN:
			break;
		case SC_PAGE_UP:
			break;
		case SC_PAGE_DOWN:
			break;
		case SC_THUMB:
			break;
		case SC_THUMBTRACK:
			break;
		default:
			break;
		}
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		/*
			No menubar was associated with this window
		*/
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case PROFILE_WINDOW_PUSHBUTTON_37: /* "OK" */
			{
			/* TAG BEGIN PROFILE_WINDOW_PUSHBUTTON_37 EVNT:Control */
						/* ********************************** */
						/* save all the options in the window */
			saveProfileOptions (xdWindow, (OBJECT *) xvt_vobj_get_data (xdWindow));
			xvt_vobj_destroy(xdWindow);
			/* TAG END PROFILE_WINDOW_PUSHBUTTON_37 EVNT:Control */
			}
			break;
		case PROFILE_WINDOW_PUSHBUTTON_38: /* "Cancel" */
			{
			/* TAG BEGIN PROFILE_WINDOW_PUSHBUTTON_38 EVNT:Control */
			OBJECT *data = (OBJECT *) xvt_vobj_get_data (xdWindow);
			copyOptions (PROFILE_WINDOW, data, OPTIONS_RESTORE);
			xvt_vobj_destroy(xdWindow);
			/* TAG END PROFILE_WINDOW_PUSHBUTTON_38 EVNT:Control */
			}
			break;
		case PROFILE_WINDOW_PUSHBUTTON_39: /* "Help..." */
			{
			/* TAG BEGIN PROFILE_WINDOW_PUSHBUTTON_39 EVNT:Control */
			displayHelp("profile.htm");
			/* TAG END PROFILE_WINDOW_PUSHBUTTON_39 EVNT:Control */
			}
			break;
		case PROFILE_LINE_JOIN: /* "Lines" */
			{
			/* TAG BEGIN PROFILE_LINE_JOIN EVNT:Control */
			xdCheckRadioButton(xdWindow, PROFILE_LINE_JOIN,
				PROFILE_LINE_JOIN, PROFILE_SQUARE_JOIN);
			updateProfileOptions (xdWindow);
			/* TAG END PROFILE_LINE_JOIN EVNT:Control */
			}
			break;
		case PROFILE_CURVE_JOIN: /* "Curves" */
			{
			/* TAG BEGIN PROFILE_CURVE_JOIN EVNT:Control */
			xdCheckRadioButton(xdWindow, PROFILE_CURVE_JOIN,
				PROFILE_LINE_JOIN, PROFILE_SQUARE_JOIN);
			updateProfileOptions (xdWindow);
			/* TAG END PROFILE_CURVE_JOIN EVNT:Control */
			}
			break;
		case PROFILE_SQUARE_JOIN: /* "Square" */
			{
			/* TAG BEGIN PROFILE_SQUARE_JOIN EVNT:Control */
			xdCheckRadioButton(xdWindow, PROFILE_SQUARE_JOIN,
				PROFILE_LINE_JOIN, PROFILE_SQUARE_JOIN);
			updateProfileOptions (xdWindow);
			/* TAG END PROFILE_SQUARE_JOIN EVNT:Control */
			}
			break;
		case PROFILE_DELETE_POINT: /* "Delete Point" */
			{
			/* TAG BEGIN PROFILE_DELETE_POINT EVNT:Control */
			extern WINDOW lastActiveWindow;
			PROFILE_OPTIONS *profOptions, *firstOptions;
#if XVT_CC_PROTO
			extern PROFILE_OPTIONS *getCurrentProfileOptions (WINDOW, PROFILE_OPTIONS *);
#else
			extern PROFILE_OPTIONS *getCurrentProfileOptions ();
#endif
			
			firstOptions = getProfileOptionsStructure ((OBJECT *) xvt_vobj_get_data(xdWindow));
			profOptions = (PROFILE_OPTIONS *) getCurrentProfileOptions (xdWindow, firstOptions);
			
			profilePointDelete (profOptions, (PROFILE_POINT *) NULL);
			        /* use lastActiveWindow to refer to drawing canvas as I had trouble geting a handle to it */
			xvt_dwin_invalidate_rect (lastActiveWindow, (RCT *) NULL);
			xvt_dwin_update(lastActiveWindow);
			/* TAG END PROFILE_DELETE_POINT EVNT:Control */
			}
			break;
		case PROFILE_DELETE_ALL: /* "Delete All" */
			{
			/* TAG BEGIN PROFILE_DELETE_ALL EVNT:Control */
			extern WINDOW lastActiveWindow;
			PROFILE_OPTIONS *profOptions, *firstOptions;
#if XVT_CC_PROTO
			extern PROFILE_OPTIONS *getCurrentProfileOptions (WINDOW, PROFILE_OPTIONS *);
#else
			extern PROFILE_OPTIONS *getCurrentProfileOptions ();
#endif
			
			firstOptions = getProfileOptionsStructure ((OBJECT *) xvt_vobj_get_data(xdWindow));
			profOptions = (PROFILE_OPTIONS *) getCurrentProfileOptions (xdWindow, firstOptions);
			profilePointDeleteAll (profOptions);
			
			        /* use lastActiveWindow to refer to drawing canvas as I had trouble geting a handle to it */
			xvt_dwin_invalidate_rect (lastActiveWindow, (RCT *) NULL);
			xvt_dwin_update(lastActiveWindow);
			/* TAG END PROFILE_DELETE_ALL EVNT:Control */
			}
			break;
		case PROFILE_CURRENT_GRAPH: /* "current Graph" */
			{
			/* TAG BEGIN PROFILE_CURRENT_GRAPH EVNT:Control */
			PROFILE_OPTIONS *firstOptions, *options;
#if XVT_CC_PROTO
			extern PROFILE_OPTIONS *getCurrentProfileOptions (WINDOW, PROFILE_OPTIONS *);
#else
			extern PROFILE_OPTIONS *getCurrentProfileOptions ();
#endif
			
			                         /* get the current profile graph structure */
			if (!(firstOptions = getProfileOptionsStructure ((OBJECT *) xvt_vobj_get_data(xdWindow))))
			   break;
			options = (PROFILE_OPTIONS *) getCurrentProfileOptions (xdWindow, firstOptions);
			
			                         /* Update the screen to show current graph */
			xdCheckRadioButton(xdWindow, PROFILE_LINE_JOIN + options->joinType,
			                                   PROFILE_LINE_JOIN, PROFILE_SQUARE_JOIN);
			
			                                         /* redraw the graph with the current selection */
			updateProfileOptions (xdWindow);
			/* TAG END PROFILE_CURRENT_GRAPH EVNT:Control */
			}
			break;
		case PROFILE_OPTIONS_BUT: /* "Options..." */
			{
			/* TAG BEGIN PROFILE_OPTIONS_BUT EVNT:Control */
			char *data = (char *) xvt_vobj_get_data (xdWindow);
			WINDOW win;
			if (!(win = createCenteredWindow(PROFILE_OPTION_WINDOW, TASK_WIN, EM_ALL, PROFILE_OPTION_WINDOW_eh, (long) data)))
				xvt_dm_post_error("Can't open window");
			/* TAG END PROFILE_OPTIONS_BUT EVNT:Control */
			}
			break;
		case PROFILE_WINDOW_HSCROLL_66: /* "Horizontal Scrollbar 66" */
			{
			/* TAG BEGIN PROFILE_WINDOW_HSCROLL_66 EVNT:Control */
			int pos = 0;
			/*
				Horizontal scrollbar control was operated
			*/
			switch (xdEvent->v.ctl.ci.v.scroll.what) {
			case SC_LINE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
				break;
			case SC_LINE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
				break;
			case SC_PAGE_UP:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - TEN;
				SNAP_DOWN_BY(pos, 10)
				break;
			case SC_PAGE_DOWN:
				pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + TEN;
				SNAP_UP_BY(pos, 10)
				break;
			case SC_THUMB:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			case SC_THUMBTRACK:
				pos = xdEvent->v.ctl.ci.v.scroll.pos;
				break;
			}
			pos = updateScrollField (xdWindow, xdControlId, pos);
			updateProfileOptions (xdWindow);
			/* TAG END PROFILE_WINDOW_HSCROLL_66 EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		XVTCM_CONTROL_INFO *xdInfo = XVTCM_GET_INFO(xdEvent);
		/* TAG BEGIN EVNT:User */
		switch (xdEvent->v.user.id) {
		case -1:
		default:
			break;
		}
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
