/*
	This file was generated by XVT-Design 4.5, a product of:

		XVT Software Inc.
		4900 Pearl East Circle
		Boulder, CO USA 80301
		303-443-4223, fax 303-443-0969

	Generated on Tue Sep 02 10:34:59 1997
*/
/* TAG BEGIN SPCL:Pre_Header */
/* TAG END SPCL:Pre_Header */

#include "xvt.h"
#include "xvtcm.h"
#include "nodInc.h"

/* 
	Information about the window
*/
#define WIN_RES_ID XYZ_GENERATION_WINDOW
#define WIN_FLAGS 0x810L
#define WIN_CLASS ""
#define WIN_BORDER W_DOC
/* TAG BEGIN SPCL:Obj_Decl */
/* TAG END SPCL:Obj_Decl */

/*
	Handler for window XYZ_GENERATION_WINDOW ("XYZ Generation")
*/
long XVT_CALLCONV1
#if XVT_CC_PROTO
XYZ_GENERATION_WINDOW_eh XVT_CALLCONV2 (WINDOW xdWindow, EVENT *xdEvent)
#else
XYZ_GENERATION_WINDOW_eh XVT_CALLCONV2 (xdWindow, xdEvent)
WINDOW xdWindow;
EVENT *xdEvent;
#endif
{
	short xdControlId = xdEvent->v.ctl.id;
	/* TAG BEGIN SPCL:Var_Decl */
	/* TAG END SPCL:Var_Decl */

	switch (xdEvent->type) {
	case E_CREATE:
		/*
			Window has been created; first event sent to newly-created
			window.
		*/
		{
		/* TAG BEGIN EVNT:Create */
		      char *object;
		      char title[100];
		      WINDOW ctlwin;
		      int mmin, mmax;
		      BLOCK_VIEW_OPTIONS *viewOptions = getViewOptions ();
		      extern GEOPHYSICS_OPTIONS geophysicsOptions;
		
		         /* put this window in the created heirachy */
		      addWinToStack (xdWindow);
		         /* ******************************** */
		         /* set the ranges of the scrollbars */
		                     /* ******************* */
		      mmin = -10000; mmax = 10000;     /* range for Position */
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_X, mmin, mmax);
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_Y, mmin, mmax);
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_Z, mmin, mmax);
		                     /* ********************** */                 
		      mmin = 0; mmax = 360;         /* range for Orientation */
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_DECL, mmin, mmax);
		                     /* **************** */                 
		      mmin = 1; mmax = 10000;       /* range for scale */
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_LLENGTH, mmin, mmax);
		      mmin = 1; mmax = 20000;
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_LHEIGHT, mmin, mmax);
		      mmin = 1; mmax = 1000;
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_LSPACING, mmin, mmax);
		      mmin = 1; mmax = 100;
		      setScrollRange (xdWindow, XYZ_GENERATION_SCROLL_PSPACING, mmin, mmax);
		
		            /* ************************ */
		            /* Assign default Values */
		      updateFloatTextField (xdWindow, XYZ_GENERATION_X, viewOptions->originX, 0);
		      updateFloatTextField (xdWindow, XYZ_GENERATION_Y, viewOptions->originY, 0);
		      updateFloatTextField (xdWindow, XYZ_GENERATION_Z, geophysicsOptions.altitude, 0);
		
		      updateFloatTextField (xdWindow, XYZ_GENERATION_LLENGTH, viewOptions->lengthX, 0);
		      updateFloatTextField (xdWindow, XYZ_GENERATION_LHEIGHT, viewOptions->lengthY, 0);
		
		            /* *************************************************** */
		            /* Check the consistency of scrollbars and text fields */
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_X, XYZ_GENERATION_X, FALSE);
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_Y, XYZ_GENERATION_Y, FALSE);
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_Z, XYZ_GENERATION_Z, FALSE);
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_DECL, XYZ_GENERATION_DECL, FALSE);
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_LLENGTH, XYZ_GENERATION_LLENGTH, FALSE);
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_LHEIGHT, XYZ_GENERATION_LHEIGHT, FALSE);
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_LSPACING, XYZ_GENERATION_LSPACING, FALSE);
		      updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_PSPACING, XYZ_GENERATION_PSPACING, FALSE);
		/* TAG END EVNT:Create */
		}
		break;
	case E_DESTROY:
		/*
			Window has been closed; last event sent to window.
		*/
		xdRemoveHelpAssoc( xdWindow );
		{
		/* TAG BEGIN EVNT:Destroy */
		         /* take this window out of the created heirachy */
		      takeWinFromStack (xdWindow);
		/* TAG END EVNT:Destroy */
		}
		break;
	case E_FOCUS:
		{
		/* TAG BEGIN EVNT:Focus */
		      /*
		         Window has lost or gained focus.
		      */
		      if (xdEvent->v.active) {
		         /*
		            Window has gained focus
		         */
		      } else {
		         /*
		            Window has lost focus
		         */
		      }
		/* TAG END EVNT:Focus */
		}
		break;
	case E_SIZE:
		/*
			Size of window has been set or changed; sent when window is
			created or subsequently resized by user or via xvt_vobj_move.
		*/
		{
		/* TAG BEGIN EVNT:Size */
		/* TAG END EVNT:Size */
		}
		break;
	case E_UPDATE:
		/*
			Window requires updating.
		*/
		{
		/* TAG BEGIN EVNT:Update */
		      xvt_dwin_clear(xdWindow, (COLOR)xvt_vobj_get_attr(xdWindow, ATTR_BACK_COLOR));
		/* TAG END EVNT:Update */
		}
		break;
	case E_CLOSE:
		/*
			Request to close window; user operated "close" menu item on
			window system menu, or operated "close" control on window
			frame. Not sent if Close on File menu is issued. Window not
			closed unless xvt_vobj_destroy is called.
		*/
		{
		/* TAG BEGIN EVNT:Close */
		      xvt_vobj_destroy(xdWindow);
		/* TAG END EVNT:Close */
		}
		break;
	case E_CHAR:
		/*
			Character typed.
		*/
		{
		/* TAG BEGIN EVNT:Char */
		         /* *********************************************** */
		         /* make a RETURN key activate the window OK Button */
		      if (xdEvent->v.chr.ch == '\r')
		      {
		         xdEvent->type = E_CONTROL;
		         xdEvent->v.ctl.id = XYZ_GENERATION_OK;
		         xvt_win_dispatch_event (xdWindow, xdEvent);
		      }
		/* TAG END EVNT:Char */
		}
		break;
	case E_MOUSE_UP:
		/*
			Mouse was released
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Up */
		/* TAG END EVNT:Mouse_Up */
		}
		break;
	case E_MOUSE_DOWN:
		/*
			Mouse was pressed
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Down */
		/* TAG END EVNT:Mouse_Down */
		}
		break;
	case E_MOUSE_DBL:
		/*
			Mouse was double clicked
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Dbl */
		/* TAG END EVNT:Mouse_Dbl */
		}
		break;
	case E_MOUSE_MOVE:
		/*
			Mouse was moved
		*/
		{
		/* TAG BEGIN EVNT:Mouse_Move */
		/* TAG END EVNT:Mouse_Move */
		}
		break;
	case E_HSCROLL:
		{
		/* TAG BEGIN EVNT:Hscroll */
		      /*
		         Horizontal scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Hscroll */
		}
		break;
	case E_VSCROLL:
		{
		/* TAG BEGIN EVNT:Vscroll */
		      /*
		         Vertical scrollbar on frame was operated
		      */
		      switch (xdEvent->v.scroll.what) {
		      case SC_LINE_UP:
		         break;
		      case SC_LINE_DOWN:
		         break;
		      case SC_PAGE_UP:
		         break;
		      case SC_PAGE_DOWN:
		         break;
		      case SC_THUMB:
		         break;
		      case SC_THUMBTRACK:
		         break;
		      default:
		         break;
		      }
		/* TAG END EVNT:Vscroll */
		}
		break;
	case E_COMMAND:
		/*
			User issued command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Command */
		      /*
		         No menubar was associated with this window
		      */
		/* TAG END EVNT:Command */
		}
		break;
	case E_CONTROL:
		/*
			User operated control in window.
		*/
		{
		/* TAG BEGIN SPCL:Control_Decl */
		/* TAG END SPCL:Control_Decl */

		switch(xdControlId) {
		case XYZ_GENERATION_SCROLL_PSPACING: /* "spacing between points" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_PSPACING EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - TEN;
			            SNAP_DOWN_BY(pos, 10)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + TEN;
			            SNAP_UP_BY(pos, 10)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_PSPACING, pos);
			/* TAG END XYZ_GENERATION_SCROLL_PSPACING EVNT:Control */
			}
			break;
		case XYZ_GENERATION_SCROLL_DECL: /* "scroll decl" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_DECL EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - TEN;
			            SNAP_DOWN_BY(pos, 10)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + TEN;
			            SNAP_UP_BY(pos, 10)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_DECL, pos);
			/* TAG END XYZ_GENERATION_SCROLL_DECL EVNT:Control */
			}
			break;
		case XYZ_GENERATION_PSPACING: /* "50" */
			{
			/* TAG BEGIN XYZ_GENERATION_PSPACING EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_PSPACING, XYZ_GENERATION_PSPACING, FALSE);
			         }
			/* TAG END XYZ_GENERATION_PSPACING EVNT:Control */
			}
			break;
		case XYZ_GENERATION_DECL: /* "90" */
			{
			/* TAG BEGIN XYZ_GENERATION_DECL EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_DECL, XYZ_GENERATION_DECL, FALSE);
			         }
			/* TAG END XYZ_GENERATION_DECL EVNT:Control */
			}
			break;
		case XYZ_GENERATION_OK: /* "OK" */
			{
			/* TAG BEGIN XYZ_GENERATION_OK EVNT:Control */
			         {
			            double xPos, yPos, zPos, decl, lineLength, lineHeight, lineSpacing, pointSpacing;
			            int fileType;
			            FILE_SPEC fs;
			            getCurrentFileName (&fs);
			            if (!strlen(fs.name))
			               strcpy (fs.name,"untitled.geo");
			            else
			               addFileExtention(fs.name, ".geo");
#if (XVTWS == MACWS)
			            strcpy (fs.type, "Nody");
#else
			            strcpy (fs.type, "geo");
#endif
			            getDefaultDirectory(&(fs.dir));
			            switch (xvt_dm_post_file_save(&fs, "Save XYZ as ...")) {
			            case FL_OK:
			               if (strlen(fs.name) == 0)
			               {
			                  xvt_dm_post_error ("Error, No file Specified");
			                  break;
			               }
			               setDefaultDirectory(&(fs.dir));
			               xvt_fsys_set_dir(&fs.dir);
			               xPos = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_X);
			               yPos = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_Y);
			               zPos = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_Z);
			               decl = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_DECL);
			               lineLength = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_LLENGTH);
			               lineHeight = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_LHEIGHT);
			               lineSpacing = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_LSPACING);
			               pointSpacing = getFloatTextFieldValue (xdWindow, XYZ_GENERATION_PSPACING);
			               fileType = xvt_ctl_is_checked (xvt_win_get_ctl (xdWindow, XYZ_GENERATION_WINDOW__C2a));
			               saveLineOfPoints (fs.name, fileType, xPos, yPos, zPos, decl, lineLength, lineHeight, lineSpacing, pointSpacing);
			               xvt_vobj_destroy(xdWindow);
			               break;
			            case FL_BAD:
			               break;
			            case FL_CANCEL:
			               break;
			            }
			         }
			/* TAG END XYZ_GENERATION_OK EVNT:Control */
			}
			break;
		case XYZ_GENERATION_CANCEL: /* "Cancel" */
			{
			/* TAG BEGIN XYZ_GENERATION_CANCEL EVNT:Control */
			         xvt_vobj_destroy(xdWindow);
			/* TAG END XYZ_GENERATION_CANCEL EVNT:Control */
			}
			break;
		case XYZ_GENERATION_HELP: /* "Help..." */
			{
			/* TAG BEGIN XYZ_GENERATION_HELP EVNT:Control */
			displayHelp("gensurv.htm");
			/* TAG END XYZ_GENERATION_HELP EVNT:Control */
			}
			break;
		case XYZ_GENERATION_X: /* "0" */
			{
			/* TAG BEGIN XYZ_GENERATION_X EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_X, XYZ_GENERATION_X, FALSE);
			         }
			/* TAG END XYZ_GENERATION_X EVNT:Control */
			}
			break;
		case XYZ_GENERATION_Z: /* "5000" */
			{
			/* TAG BEGIN XYZ_GENERATION_Z EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_Y, XYZ_GENERATION_Y, FALSE);
			         }
			/* TAG END XYZ_GENERATION_Z EVNT:Control */
			}
			break;
		case XYZ_GENERATION_Y: /* "0" */
			{
			/* TAG BEGIN XYZ_GENERATION_Y EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_Z, XYZ_GENERATION_Z, FALSE);
			         }
			/* TAG END XYZ_GENERATION_Y EVNT:Control */
			}
			break;
		case XYZ_GENERATION_SCROLL_X: /* "Horizontal Scrollbar 101" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_X EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos, 1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos, 1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_X, pos);
			/* TAG END XYZ_GENERATION_SCROLL_X EVNT:Control */
			}
			break;
		case XYZ_GENERATION_SCROLL_Y: /* "Horizontal Scrollbar 102" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_Y EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos, 1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos, 1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_Y, pos);
			/* TAG END XYZ_GENERATION_SCROLL_Y EVNT:Control */
			}
			break;
		case XYZ_GENERATION_SCROLL_Z: /* "Horizontal Scrollbar 103" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_Z EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos, 1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos, 1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_Z, pos);
			/* TAG END XYZ_GENERATION_SCROLL_Z EVNT:Control */
			}
			break;
		case XYZ_GENERATION_SCROLL_LLENGTH: /* "along lines" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_LLENGTH EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos, 1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos, 1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_LLENGTH, pos);
			/* TAG END XYZ_GENERATION_SCROLL_LLENGTH EVNT:Control */
			}
			break;
		case XYZ_GENERATION_LLENGTH: /* "8000" */
			{
			/* TAG BEGIN XYZ_GENERATION_LLENGTH EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_LLENGTH, XYZ_GENERATION_LLENGTH, FALSE);
			         }
			/* TAG END XYZ_GENERATION_LLENGTH EVNT:Control */
			}
			break;
		case XYZ_GENERATION_SCROLL_LSPACING: /* "spacing between lines" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_LSPACING EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - HUNDRED;
			            SNAP_DOWN_BY(pos, 100)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + HUNDRED;
			            SNAP_UP_BY(pos, 100)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_LSPACING, pos);
			/* TAG END XYZ_GENERATION_SCROLL_LSPACING EVNT:Control */
			}
			break;
		case XYZ_GENERATION_LSPACING: /* "500" */
			{
			/* TAG BEGIN XYZ_GENERATION_LSPACING EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_LSPACING, XYZ_GENERATION_LSPACING, FALSE);
			         }
			/* TAG END XYZ_GENERATION_LSPACING EVNT:Control */
			}
			break;
		case XYZ_GENERATION_SCROLL_LHEIGHT: /* "across lines" */
			{
			/* TAG BEGIN XYZ_GENERATION_SCROLL_LHEIGHT EVNT:Control */
			         int pos = 0;
			         /*
			            Horizontal scrollbar control was operated
			         */
			         switch (xdEvent->v.ctl.ci.v.scroll.what) {
			         case SC_LINE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - 1;
			            break;
			         case SC_LINE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + 1;
			            break;
			         case SC_PAGE_UP:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) - THOUSAND;
			            SNAP_DOWN_BY(pos, 1000)
			            break;
			         case SC_PAGE_DOWN:
			            pos = xvt_sbar_get_pos (xdEvent->v.ctl.ci.win, HVSCROLL) + THOUSAND;
			            SNAP_UP_BY(pos, 1000)
			            break;
			         case SC_THUMB:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         case SC_THUMBTRACK:
			            pos = xdEvent->v.ctl.ci.v.scroll.pos;
			            break;
			         }
			         pos = updateScrollField (xdWindow, xdControlId, pos);
			         updateNumericTextField (xdWindow, XYZ_GENERATION_LHEIGHT, pos);
			/* TAG END XYZ_GENERATION_SCROLL_LHEIGHT EVNT:Control */
			}
			break;
		case XYZ_GENERATION_LHEIGHT: /* "10000" */
			{
			/* TAG BEGIN XYZ_GENERATION_LHEIGHT EVNT:Control */
			         /*
			            Edit control was operated.
			         */
			         if (xdEvent->v.ctl.ci.v.edit.focus_change) {
			            if (xdEvent->v.ctl.ci.v.edit.active) {
			               /*
			                  focus has entered the control
			               */
			            } else {
			               /*
			                  focus has left the control
			               */
			            }
			         } else {
			            /*
			               Contents of control were changed
			            */
			         updateScrollAndText (xdWindow, XYZ_GENERATION_SCROLL_LLENGTH, XYZ_GENERATION_LLENGTH, FALSE);
			         }
			/* TAG END XYZ_GENERATION_LHEIGHT EVNT:Control */
			}
			break;
		case XYZ_GENERATION_WINDOW__C1a: /* "Geological" */
			{
			/* TAG BEGIN XYZ_GENERATION_WINDOW__C1a EVNT:Control */
			         xdCheckRadioButton(xdWindow,
			            XYZ_GENERATION_WINDOW__C1a,
			            XYZ_GENERATION_WINDOW__C1a,
			            XYZ_GENERATION_WINDOW__C2a);
			/* TAG END XYZ_GENERATION_WINDOW__C1a EVNT:Control */
			}
			break;
		case XYZ_GENERATION_WINDOW__C2a: /* "Geophysical" */
			{
			/* TAG BEGIN XYZ_GENERATION_WINDOW__C2a EVNT:Control */
			         xdCheckRadioButton(xdWindow,
			            XYZ_GENERATION_WINDOW__C2a,
			            XYZ_GENERATION_WINDOW__C1a,
			            XYZ_GENERATION_WINDOW__C2a);
			/* TAG END XYZ_GENERATION_WINDOW__C2a EVNT:Control */
			}
			break;
		default:
			break;
		}
		}
		break;
	case E_FONT:
		/*
			User issued font command on window menu bar (menu bar at top of
			screen for Mac/CH).
		*/
		{
		/* TAG BEGIN EVNT:Font */
		/* TAG END EVNT:Font */
		}
		break;
	case E_TIMER:
		/*
			Timer associated with window went off.
		*/
		{
		/* TAG BEGIN EVNT:Timer */
		/* TAG END EVNT:Timer */
		}
		break;
	case E_USER:
		/*
			Application initiated.
		*/
		{
		/* TAG BEGIN EVNT:User */
		      switch (xdEvent->v.user.id) {
		      case -1:
		      default:
		         break;
		      }
		/* TAG END EVNT:User */
		}
		break;
	default:
		break;
	}
	/* TAG BEGIN SPCL:Bottom */
#ifdef XVT_R40_TXEDIT_BEHAVIOR
	   xvt_tx_process_event(xdWindow, xdEvent);
#endif
	/* TAG END SPCL:Bottom */
	return 0L;
}
